"""Public Macro decision-system interface."""

from .acquisition_worker import MacroAcquisitionWorker
from .backfill import MacroBackfillPolicy, professional_backfill_policies
from .calculations import (
    CALCULATION_REGISTRY,
    NATURAL_CHANGE_REGISTRY,
    CalculationSpec,
    NaturalChangeCalculationSpec,
    natural_change_calculation,
)
from .coverage import COVERAGE_MANIFEST, CoverageSpec, coverage_for_module
from .document_analysis_worker import MacroDocumentAnalysisWorker
from .domain import (
    MACRO_MODULE_IDS,
    MACRO_MODULE_LABELS,
    DatasetSpec,
    DocumentFact,
    FedOfficialRoleFact,
    FetchBatch,
    MacroClockKind,
    MacroFactFamily,
    MacroModuleId,
    MacroSourceClientProtocol,
    MacroSourceError,
    MacroSourceUnavailable,
    MarketObservationFact,
    MarketSettlementFact,
    ReleaseFact,
    SeriesFact,
)
from .fed_analysis import (
    FedAnalysisEvidence,
    FedDocumentAnalysisDraft,
    MacroDocumentAnalysisService,
)
from .module_payloads import build_typed_module_payload, schema_version_for_module
from .projection_worker import MacroProjectionWorker
from .read_models import (
    MacroAssetHorizonPresentation,
    MacroAssetPresentation,
    MacroClaimAssetImplication,
    MacroClaimPresentation,
    MacroConditionAnnotation,
    MacroLiveDeltaItemRead,
    MacroLiveDeltaRead,
    MacroLiveDeltaScope,
    MacroOutcomeAssetResultRead,
    MacroOutcomeHorizonRead,
    MacroOutcomeReplayRead,
    MacroPublicationAppendixRead,
    MacroPublicationDataQualityRead,
    MacroPublicationModuleQualityRead,
    MacroPublicationSourceLineageRead,
    MacroReconciliationComparisonRead,
    MacroReconciliationObservationRead,
    MacroReconciliationReceiptRead,
    project_asset_presentation,
    project_claim_presentation,
    project_live_delta_for_read,
    project_module_annotations,
    project_outcome_replay_for_read,
    project_publication_appendix,
)
from .reasons import MacroReason, MacroReasonImpact, MacroReasonRecovery, macro_reason
from .registry import DATASET_REGISTRY, datasets_for_clock, datasets_for_module, require_dataset
from .repository import MacroRepository
from .thesis import (
    MACRO_EVIDENCE_PACK_SCHEMA_VERSION,
    MACRO_LIVE_DELTA_SCHEMA_VERSION,
    MACRO_OUTCOME_REPLAY_SCHEMA_VERSION,
    MACRO_THESIS_ASSETS,
    MACRO_THESIS_OUTCOME_DATASETS,
    MACRO_THESIS_SCHEMA_VERSION,
    MacroAlternative,
    MacroAssetOutlook,
    MacroCausalEdge,
    MacroChangeFromPrior,
    MacroCondition,
    MacroEvidencePackV3,
    MacroHorizonOutlook,
    MacroLiveDeltaV1,
    MacroMainline,
    MacroModuleRole,
    MacroNarrativeSection,
    MacroOutcomeReplayV1,
    MacroTension,
    MacroTensionSide,
    MacroThesisBodyDraft,
    MacroThesisClaim,
    MacroThesisReviewV1,
    MacroThesisV1,
    compile_evidence_pack_v3,
    evaluate_live_delta,
    evaluate_outcome_replay,
    payload_hash,
)
from .thesis_repository import MacroThesisRepository
from .thesis_service import MacroThesisService, resolve_thesis_session, thesis_cutoff_ms
from .thesis_worker import MacroThesisWorker

__all__ = [
    "CALCULATION_REGISTRY",
    "COVERAGE_MANIFEST",
    "DATASET_REGISTRY",
    "MACRO_EVIDENCE_PACK_SCHEMA_VERSION",
    "MACRO_LIVE_DELTA_SCHEMA_VERSION",
    "MACRO_MODULE_IDS",
    "MACRO_MODULE_LABELS",
    "MACRO_OUTCOME_REPLAY_SCHEMA_VERSION",
    "MACRO_THESIS_ASSETS",
    "MACRO_THESIS_OUTCOME_DATASETS",
    "MACRO_THESIS_SCHEMA_VERSION",
    "NATURAL_CHANGE_REGISTRY",
    "CalculationSpec",
    "CoverageSpec",
    "DatasetSpec",
    "DocumentFact",
    "FedAnalysisEvidence",
    "FedDocumentAnalysisDraft",
    "FedOfficialRoleFact",
    "FetchBatch",
    "MacroAcquisitionWorker",
    "MacroAlternative",
    "MacroAssetHorizonPresentation",
    "MacroAssetOutlook",
    "MacroAssetPresentation",
    "MacroBackfillPolicy",
    "MacroCausalEdge",
    "MacroChangeFromPrior",
    "MacroClaimAssetImplication",
    "MacroClaimPresentation",
    "MacroClockKind",
    "MacroCondition",
    "MacroConditionAnnotation",
    "MacroDocumentAnalysisService",
    "MacroDocumentAnalysisWorker",
    "MacroEvidencePackV3",
    "MacroFactFamily",
    "MacroHorizonOutlook",
    "MacroLiveDeltaItemRead",
    "MacroLiveDeltaRead",
    "MacroLiveDeltaScope",
    "MacroLiveDeltaV1",
    "MacroMainline",
    "MacroModuleId",
    "MacroModuleRole",
    "MacroNarrativeSection",
    "MacroOutcomeAssetResultRead",
    "MacroOutcomeHorizonRead",
    "MacroOutcomeReplayRead",
    "MacroOutcomeReplayV1",
    "MacroProjectionWorker",
    "MacroPublicationAppendixRead",
    "MacroPublicationDataQualityRead",
    "MacroPublicationModuleQualityRead",
    "MacroPublicationSourceLineageRead",
    "MacroReason",
    "MacroReasonImpact",
    "MacroReasonRecovery",
    "MacroReconciliationComparisonRead",
    "MacroReconciliationObservationRead",
    "MacroReconciliationReceiptRead",
    "MacroRepository",
    "MacroSourceClientProtocol",
    "MacroSourceError",
    "MacroSourceUnavailable",
    "MacroTension",
    "MacroTensionSide",
    "MacroThesisBodyDraft",
    "MacroThesisClaim",
    "MacroThesisRepository",
    "MacroThesisReviewV1",
    "MacroThesisService",
    "MacroThesisV1",
    "MacroThesisWorker",
    "MarketObservationFact",
    "MarketSettlementFact",
    "NaturalChangeCalculationSpec",
    "ReleaseFact",
    "SeriesFact",
    "build_typed_module_payload",
    "compile_evidence_pack_v3",
    "coverage_for_module",
    "datasets_for_clock",
    "datasets_for_module",
    "evaluate_live_delta",
    "evaluate_outcome_replay",
    "macro_reason",
    "natural_change_calculation",
    "payload_hash",
    "professional_backfill_policies",
    "project_asset_presentation",
    "project_claim_presentation",
    "project_live_delta_for_read",
    "project_module_annotations",
    "project_outcome_replay_for_read",
    "project_publication_appendix",
    "require_dataset",
    "resolve_thesis_session",
    "schema_version_for_module",
    "thesis_cutoff_ms",
]
