"""Public Macro decision-system interface."""

from .acquisition_worker import MacroAcquisitionWorker
from .domain import (
    MACRO_MODULE_IDS,
    MACRO_MODULE_LABELS,
    DatasetSpec,
    DocumentFact,
    FetchBatch,
    MacroClockKind,
    MacroFactFamily,
    MacroModuleId,
    MacroSourceClientProtocol,
    MacroSourceError,
    MacroSourceUnavailable,
    MarketObservationFact,
    MarketSettlementFact,
    ReleaseFact,
    SeriesFact,
)
from .judgment_worker import MacroJudgmentWorker
from .projection_worker import MacroProjectionWorker
from .registry import DATASET_REGISTRY, datasets_for_clock, datasets_for_module, require_dataset
from .repository import MacroRepository
from .research.completed_session import CompletedSessionMacro, resolve_completed_session
from .research.repository import MacroResearchRepository, PostgresMacroResearchReadPort
from .research.service import (
    MACRO_RESEARCH_MAX_PRIOR_PUBLICATIONS_PER_PAGE,
    MACRO_RESEARCH_MAX_READ_REFS,
    FrozenMacroEvidenceScope,
    MacroEvidenceQuery,
    MacroEvidenceRecord,
    MacroResearchAgentResult,
    MacroResearchArtifactDraft,
    MacroResearchAudit,
    MacroResearchIntegrityError,
    MacroResearchReadPort,
    canonicalize_macro_research_artifact,
    require_artifact_integrity,
    require_catalog_in_scope,
    require_evidence_in_scope,
    require_prior_research_in_scope,
)
from .research.worker import MacroResearchWorker

__all__ = [
    "DATASET_REGISTRY",
    "MACRO_MODULE_IDS",
    "MACRO_MODULE_LABELS",
    "MACRO_RESEARCH_MAX_PRIOR_PUBLICATIONS_PER_PAGE",
    "MACRO_RESEARCH_MAX_READ_REFS",
    "CompletedSessionMacro",
    "DatasetSpec",
    "DocumentFact",
    "FetchBatch",
    "FrozenMacroEvidenceScope",
    "MacroAcquisitionWorker",
    "MacroClockKind",
    "MacroEvidenceQuery",
    "MacroEvidenceRecord",
    "MacroFactFamily",
    "MacroJudgmentWorker",
    "MacroModuleId",
    "MacroProjectionWorker",
    "MacroRepository",
    "MacroResearchAgentResult",
    "MacroResearchArtifactDraft",
    "MacroResearchAudit",
    "MacroResearchIntegrityError",
    "MacroResearchReadPort",
    "MacroResearchRepository",
    "MacroResearchWorker",
    "MacroSourceClientProtocol",
    "MacroSourceError",
    "MacroSourceUnavailable",
    "MarketObservationFact",
    "MarketSettlementFact",
    "PostgresMacroResearchReadPort",
    "ReleaseFact",
    "SeriesFact",
    "canonicalize_macro_research_artifact",
    "datasets_for_clock",
    "datasets_for_module",
    "require_artifact_integrity",
    "require_catalog_in_scope",
    "require_dataset",
    "require_evidence_in_scope",
    "require_prior_research_in_scope",
    "resolve_completed_session",
]
