"""WorldMonitor-compatible RSS -> NewsItem -> Story -> World Brief seam."""

from .classification import (
    SEVERITY_VALUES,
    bounded_ai_classification,
    classify_by_keyword,
    has_historical_marker,
)
from .identity import (
    STORY_SIMILARITY_THRESHOLD,
    candidate_tokens,
    cluster_texts,
    is_same_story,
    normalize_story_text,
    story_similarity,
    story_vector,
)
from .interface import NewsInterface
from .models import (
    AI_CLASSIFIER_PROMPT_VERSION,
    BRIEF_PROMPT_VERSION,
    BRIEF_SCHEMA_VERSION,
    BRIEF_WORKFLOW_VERSION,
    CLASSIFIER_VERSION,
    IMPORTANCE_VERSION,
    NEWS_LOCALE,
    SOURCE_INVENTORY_VERSION,
    STORY_IDENTITY_VERSION,
    NewsBriefDraft,
    NewsBriefPublisher,
    NewsBriefStory,
    NewsClassification,
    NewsClassificationPublisher,
    NewsFeedEntry,
    NewsFeedFetch,
    NewsFeedReader,
    NewsSourceDefinition,
    source_definition,
)
from .ranking import importance_score, is_delayed_brief_excluded, select_top_stories
from .repository import NewsRepository
from .sources import WORLDMONITOR_COMMIT, default_sources
from .workers import NewsAiClassifyWorker, NewsPipelineWorker, NewsWorldBriefWorker

__all__ = [
    "AI_CLASSIFIER_PROMPT_VERSION",
    "BRIEF_PROMPT_VERSION",
    "BRIEF_SCHEMA_VERSION",
    "BRIEF_WORKFLOW_VERSION",
    "CLASSIFIER_VERSION",
    "IMPORTANCE_VERSION",
    "NEWS_LOCALE",
    "SEVERITY_VALUES",
    "SOURCE_INVENTORY_VERSION",
    "STORY_IDENTITY_VERSION",
    "STORY_SIMILARITY_THRESHOLD",
    "WORLDMONITOR_COMMIT",
    "NewsAiClassifyWorker",
    "NewsBriefDraft",
    "NewsBriefPublisher",
    "NewsBriefStory",
    "NewsClassification",
    "NewsClassificationPublisher",
    "NewsFeedEntry",
    "NewsFeedFetch",
    "NewsFeedReader",
    "NewsInterface",
    "NewsPipelineWorker",
    "NewsRepository",
    "NewsSourceDefinition",
    "NewsWorldBriefWorker",
    "bounded_ai_classification",
    "candidate_tokens",
    "classify_by_keyword",
    "cluster_texts",
    "default_sources",
    "has_historical_marker",
    "importance_score",
    "is_delayed_brief_excluded",
    "is_same_story",
    "normalize_story_text",
    "select_top_stories",
    "source_definition",
    "story_similarity",
    "story_vector",
]
