"""`tracefold.trading`: the capital/order bounded context (#104).

The public Python interface of this capability is this package root, exactly as `tracefold.news` is for
News. Nothing outside imports a submodule; the composition root (`tracefold.app`) is the only place
that knows both business packages, and it is where News projections become Trading inputs.

The context owns: what may become a case, the deterministic OI/price regime, one `dspy.Predict`
judgement, the pure trade policy, deterministic sizing, and the durable one-attempt order ledger. It
owns no News truth, parses no provider frame, and writes no News table.
"""

from __future__ import annotations

from .blacklist import Blacklist, BlacklistEntry
from .candidates import (
    DEFAULT_ELIGIBILITY,
    EligibilityPolicy,
    Funnel,
    Rejected,
    attach_news,
    attach_oi,
    blacklist_rule,
    news_candidate,
    oi_candidate,
    resolve_instrument,
)
from .decision_program import (
    DEFAULT_DEADLINE_SECONDS,
    DEFAULT_MAX_TOKENS,
    NewsOiTradeDecision,
    ProgramIdentity,
    TradingDecisionProgram,
    assert_model_input_safe,
    build_inputs,
)
from .models import (
    ACTIVE_ORDER_STATES,
    TERMINAL_ORDER_STATES,
    TRADING_MANIFEST_VERSION,
    TRADING_POLICY_VERSION,
    TRADING_PROGRAM_VERSION,
    Bar,
    CaseKind,
    CaseState,
    ControlState,
    ExchangeId,
    ExecutionReceipt,
    InstrumentRef,
    MarketContext,
    NewsTradeCandidate,
    OiRegime,
    OiTradeCandidate,
    OrderSide,
    OrderState,
    PolicyDecision,
    PolicyOutcome,
    PreparedOrder,
    RegimeAssessment,
    RiskRejection,
    TradeDecision,
    TradingCaseManifest,
    TradingMode,
    canonical_base_symbol,
    canonical_sha256,
    underlying_key,
)
from .order import (
    DEFAULT_ORDER_POLICY,
    OrderPolicy,
    SizedOrder,
    build_payload,
    must_close_at,
    realized_bps,
    size_order,
)
from .paper import PaperAdapter, PaperFaults, evaluate_paper_exit
from .pipeline import (
    BarFetcher,
    BarFetcherFactory,
    CandidateRunner,
    ReconcileRunner,
    TradingConfig,
    TradingPipeline,
    build_pipeline,
    commit_order,
)
from .policy import DEFAULT_TRADE_POLICY, TradePolicy, decide, deterministic_side, pre_model_reject, side_to_order_side
from .regime import DEFAULT_REGIME_POLICY, RegimePolicy, assess, permits_entry, pre_move_bps, regime_side
from .repository import TradingRepository

__all__ = [
    "ACTIVE_ORDER_STATES",
    "DEFAULT_DEADLINE_SECONDS",
    "DEFAULT_ELIGIBILITY",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_ORDER_POLICY",
    "DEFAULT_REGIME_POLICY",
    "DEFAULT_TRADE_POLICY",
    "TERMINAL_ORDER_STATES",
    "TRADING_MANIFEST_VERSION",
    "TRADING_POLICY_VERSION",
    "TRADING_PROGRAM_VERSION",
    "Bar",
    "BarFetcher",
    "BarFetcherFactory",
    "Blacklist",
    "BlacklistEntry",
    "CandidateRunner",
    "CaseKind",
    "CaseState",
    "ControlState",
    "EligibilityPolicy",
    "ExchangeId",
    "ExecutionReceipt",
    "Funnel",
    "InstrumentRef",
    "MarketContext",
    "NewsOiTradeDecision",
    "NewsTradeCandidate",
    "OiRegime",
    "OiTradeCandidate",
    "OrderPolicy",
    "OrderSide",
    "OrderState",
    "PaperAdapter",
    "PaperFaults",
    "PolicyDecision",
    "PolicyOutcome",
    "PreparedOrder",
    "ProgramIdentity",
    "ReconcileRunner",
    "RegimeAssessment",
    "RegimePolicy",
    "Rejected",
    "RiskRejection",
    "SizedOrder",
    "TradeDecision",
    "TradePolicy",
    "TradingCaseManifest",
    "TradingConfig",
    "TradingDecisionProgram",
    "TradingMode",
    "TradingPipeline",
    "TradingRepository",
    "assert_model_input_safe",
    "assess",
    "attach_news",
    "attach_oi",
    "blacklist_rule",
    "build_inputs",
    "build_payload",
    "build_pipeline",
    "canonical_base_symbol",
    "canonical_sha256",
    "commit_order",
    "decide",
    "deterministic_side",
    "evaluate_paper_exit",
    "must_close_at",
    "news_candidate",
    "oi_candidate",
    "permits_entry",
    "pre_model_reject",
    "pre_move_bps",
    "realized_bps",
    "regime_side",
    "resolve_instrument",
    "side_to_order_side",
    "size_order",
    "underlying_key",
]
