"""Public Case and TradeIntent values for the Trading bounded context."""

from __future__ import annotations

from .accounts import trading_credential_fingerprint, trading_provider_account_fingerprint
from .candidate.blacklist import BlacklistSnapshotV1
from .capabilities import (
    ExecutionCapabilitySnapshotV1,
    ExecutionInstrumentCapabilityV1,
    ExecutionUniverseCandidateRow,
    ProviderInstrumentCandidateV1,
    StableCapabilityExclusionV1,
)
from .contracts import (
    Bar,
    CaseState,
    InstrumentRef,
    TradingCaseManifest,
)
from .intent import (
    ACTIVE_INTENT_STATES,
    INTENT_POLICY_SHA256,
    IntentOutcome,
    IntentReasonCode,
    TradeIntent,
    deterministic_client_order_id,
)
from .manual import (
    ManualAccountSnapshot,
    ManualModificationGuard,
    ManualRiskConfig,
    ManualSessionState,
    ManualStrategyPresetConfig,
    ManualTradeIntent,
    ManualTradeParameters,
    ManualTradePreview,
    ManualTradeRecommendation,
    ManualTradeSession,
    ManualTradeSource,
    ManualVenue,
    ModificationGuardState,
    StrategyPreset,
    TradeSide,
    build_manual_trade_preview,
    create_manual_trade_intent,
    guard_manual_trade_modification,
    recommend_manual_trade,
)
from .manual_execution import ManualExecutionPlan, build_manual_execution_plan
from .manual_executor import (
    ManualAttemptLeg,
    ManualExecutionRecord,
    ManualExecutionService,
    ManualExecutionState,
    ManualExecutionStore,
    ManualExecutionVenue,
    ManualOrderLeg,
    ManualProtectionExecutionRecord,
    ManualReconciliationResult,
    ManualTradeOutcome,
    ManualTradeOutcomeState,
    ManualVenueAccount,
    ManualVenueError,
    ManualVenueInstrument,
    ManualVenueOrderReceipt,
    ManualVenuePosition,
)
from .manual_ledger import ManualTradeEvent, ManualTradeEventKind, create_manual_trade_event
from .replay import (
    BAR_FIDELITY_VERSION,
    ReplayArtifactV1,
    ReplayBarV1,
    ReplayExecutionIntentV1,
    ReplayReceiptV1,
    ReplayScenarioCapabilityV1,
    ReplaySpecV1,
    ReplayTerminalOutcomeV1,
)

__all__ = [
    "ACTIVE_INTENT_STATES",
    "BAR_FIDELITY_VERSION",
    "INTENT_POLICY_SHA256",
    "Bar",
    "BlacklistSnapshotV1",
    "CaseState",
    "ExecutionCapabilitySnapshotV1",
    "ExecutionInstrumentCapabilityV1",
    "ExecutionUniverseCandidateRow",
    "InstrumentRef",
    "IntentOutcome",
    "IntentReasonCode",
    "ManualAccountSnapshot",
    "ManualAttemptLeg",
    "ManualExecutionPlan",
    "ManualExecutionRecord",
    "ManualExecutionService",
    "ManualExecutionState",
    "ManualExecutionStore",
    "ManualExecutionVenue",
    "ManualModificationGuard",
    "ManualOrderLeg",
    "ManualProtectionExecutionRecord",
    "ManualReconciliationResult",
    "ManualRiskConfig",
    "ManualSessionState",
    "ManualStrategyPresetConfig",
    "ManualTradeEvent",
    "ManualTradeEventKind",
    "ManualTradeIntent",
    "ManualTradeOutcome",
    "ManualTradeOutcomeState",
    "ManualTradeParameters",
    "ManualTradePreview",
    "ManualTradeRecommendation",
    "ManualTradeSession",
    "ManualTradeSource",
    "ManualVenue",
    "ManualVenueAccount",
    "ManualVenueError",
    "ManualVenueInstrument",
    "ManualVenueOrderReceipt",
    "ManualVenuePosition",
    "ModificationGuardState",
    "ProviderInstrumentCandidateV1",
    "ReplayArtifactV1",
    "ReplayBarV1",
    "ReplayExecutionIntentV1",
    "ReplayReceiptV1",
    "ReplayScenarioCapabilityV1",
    "ReplaySpecV1",
    "ReplayTerminalOutcomeV1",
    "StableCapabilityExclusionV1",
    "StrategyPreset",
    "TradeIntent",
    "TradeSide",
    "TradingCaseManifest",
    "build_manual_execution_plan",
    "build_manual_trade_preview",
    "create_manual_trade_event",
    "create_manual_trade_intent",
    "deterministic_client_order_id",
    "guard_manual_trade_modification",
    "recommend_manual_trade",
    "trading_credential_fingerprint",
    "trading_provider_account_fingerprint",
]
