"""Index-driven related-Event recall (#771).

Migration evidence:

- category: News read-path indexes, two immutable SQL functions and two generated retrieval columns on
  `news_event_assets`.
- why_database_must_change: the #761 recall query evaluated every Event of the 30-day window per call
  (trigram similarity against every member fact, a regexp-normalised code for every asset row, an OR across two
  item columns) and overran the 3 s Workers statement timeout. Each channel now starts from an index:
  - explicit: `news_items.canonical_url` (the artifact lookup already has `ix_news_items_source_artifact`) and
    `news_events.leader_item_id`;
  - entity: `retrieval_symbol` / `retrieval_pair_base`, generated by PostgreSQL with exactly the normalisation
    the query applied per row (edge whitespace and `$` trimmed, address spellings kept, upper case, `XYZ-` and
    venue `prefix:` stripped; the first crypto quote suffix of USDT, USDC, FDUSD, TUSD, BUSD, USD for a crypto
    or unknown tag). Catalogue aliases stay code-owned: the query expands them, the column stores no alias;
  - similarity: a GIN trigram index on `news_event_members.fact_text`. The GiST title index that only the old
    similarity scan used is dropped.
- current_source_revision: 20260929_0418
- minimum_supported_source_revision: 20260929_0418
- lock_level_and_order: `news_event_assets` ACCESS EXCLUSIVE while ADD COLUMN ... STORED rewrites it (34k rows
  in production), then SHARE for each CREATE INDEX (`news_event_assets`, `news_items`, `news_events`,
  `news_event_members`), then ACCESS EXCLUSIVE on `news_events` for the DROP INDEX. Writers are stopped by the
  normal migrate-before-start order; nothing outside `news_event_assets` is rewritten.
- statement_timeout: 600s locally; lock_timeout: 5s locally. On a copy of production (64k Items, 40k Events,
  57k members, 34k assets) the revision ran in under 3 s.
- estimated_rows: the rewrite computes the generated values of every existing asset row; no other backfill.
- preflight_and_maintenance_boundary: none. The previous image never names the new columns and the database
  computes them on its inserts, so rolling the image back keeps writing correct rows.
- archive_current_compatibility: no fact, revision or delivery row changes.
- role_and_grant_impact: none.
- failure_state: transactional DDL rollback.
- roll_forward_or_verified_backup_restore: downgrade drops the new columns, functions and indexes and recreates
  the GiST title index; no data is lost either way.

Revision ID: 20261001_0419
Revises: 20260929_0418
"""

from alembic import op

revision = "20261001_0419"
down_revision = "20260929_0418"
branch_labels = None
depends_on = None

# Frozen copies of `tracefold.news.entities.ADDRESS_PATTERN` and `CRYPTO_QUOTE_SUFFIXES` as of this revision. A
# later change to either needs a revision that replaces both functions and recomputes the columns; the
# integration test that checks them against `asset_retrieval_symbols` fails until it exists.
_ADDRESS = r"^(?:0[xX][0-9a-fA-F]{40}|[1-9A-HJ-NP-Za-km-z]{32,44}|solana:.*)$"
_QUOTES = ("USDT", "USDC", "FDUSD", "TUSD", "BUSD", "USD")
_TAGGED = r"regexp_replace(symbol, '^[[:space:]$]+|[[:space:]]+$', '', 'g')"
_CODE = "regexp_replace(regexp_replace(upper(tagged), '^XYZ-', ''), '^[^:]*:', '')"
_PAIR_BASE = " ".join(
    f"WHEN right(code, {len(quote)}) = '{quote}' AND length(code) > {len(quote) + 1}"
    f" THEN left(code, length(code) - {len(quote)})"
    for quote in _QUOTES
)


def _sql(statement: str) -> str:
    # The patterns contain `(?:` and `prefix:`; a backslash keeps SQLAlchemy from reading `:name` as a bind.
    return statement.replace(":", "\\:")


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '600s'")
    # SQL-standard bodies bind their objects at creation, so restores and sessions with an empty search_path
    # compute the same values.
    op.execute(
        _sql(f"""
        CREATE FUNCTION public.news_asset_retrieval_symbol(symbol text) RETURNS text
          LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
        BEGIN ATOMIC
          SELECT CASE WHEN tagged ~ '{_ADDRESS}' THEN tagged ELSE {_CODE} END
            FROM (SELECT {_TAGGED} AS tagged) AS edge;
        END
        """)  # noqa: S608 - code-owned constants only
    )
    op.execute(
        _sql(f"""
        CREATE FUNCTION public.news_asset_retrieval_pair_base(symbol text, market_type text) RETURNS text
          LANGUAGE sql IMMUTABLE PARALLEL SAFE
        BEGIN ATOMIC
          SELECT CASE WHEN COALESCE(market_type, 'unknown') IN ('crypto', 'unknown') AND tagged !~ '{_ADDRESS}'
                      THEN CASE {_PAIR_BASE} END END
            FROM (SELECT tagged, {_CODE} AS code FROM (SELECT {_TAGGED} AS tagged) AS edge) AS normalized;
        END
        """)  # noqa: S608 - code-owned constants only
    )
    op.execute("""
        ALTER TABLE public.news_event_assets
          ADD COLUMN retrieval_symbol text
            GENERATED ALWAYS AS (public.news_asset_retrieval_symbol(symbol)) STORED,
          ADD COLUMN retrieval_pair_base text
            GENERATED ALWAYS AS (public.news_asset_retrieval_pair_base(symbol, market_type)) STORED
    """)
    op.execute(
        "CREATE INDEX ix_news_event_assets_retrieval_symbol ON public.news_event_assets (retrieval_symbol, event_id)"
    )
    op.execute(
        "CREATE INDEX ix_news_event_assets_retrieval_pair_base ON public.news_event_assets"
        " (retrieval_pair_base, event_id) WHERE retrieval_pair_base IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_news_items_canonical_url ON public.news_items (canonical_url) WHERE canonical_url IS NOT NULL"
    )
    op.execute("CREATE INDEX ix_news_events_leader_item ON public.news_events (leader_item_id)")
    # fastupdate off: a probe reads posting lists only, never a pending list that a busy hour has grown.
    op.execute(
        "CREATE INDEX ix_news_event_members_fact_trgm ON public.news_event_members"
        " USING gin (fact_text public.gin_trgm_ops) WITH (fastupdate = off)"
    )
    op.execute("DROP INDEX public.ix_news_events_evidence_title")


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '600s'")
    op.execute(
        "CREATE INDEX ix_news_events_evidence_title ON public.news_events"
        " USING gist (comparison_title public.gist_trgm_ops)"
    )
    op.execute("DROP INDEX public.ix_news_event_members_fact_trgm")
    op.execute("DROP INDEX public.ix_news_events_leader_item")
    op.execute("DROP INDEX public.ix_news_items_canonical_url")
    op.execute("ALTER TABLE public.news_event_assets DROP COLUMN retrieval_pair_base, DROP COLUMN retrieval_symbol")
    op.execute("DROP FUNCTION public.news_asset_retrieval_pair_base(text, text)")
    op.execute("DROP FUNCTION public.news_asset_retrieval_symbol(text)")
