# tests/contract/test_openapi_drift.py
"""Contract test: regenerate OpenAPI + frontend types and assert no drift.

If this test fails, run `make regen-contract` to update the committed artefacts,
then commit the resulting diff so reviewers can see the schema change.

Note on types layout
--------------------
web/src/lib/types/openapi.ts  — auto-generated by openapi-typescript; only
                                OpenAPI path/component/operation interfaces live here.
web/src/api/types.ts          — temporary hand-authored domain types until the
                                frontend facade moves fully to generated contracts.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "docs" / "generated" / "openapi.json"
OPENAPI_TS_PATH = ROOT / "web" / "src" / "lib" / "types" / "openapi.ts"
FRONTEND_CONTRACTS_PATH = ROOT / "web" / "src" / "lib" / "types" / "frontend-contracts.ts"


@pytest.mark.contract
def test_openapi_json_matches_committed_artefact(tmp_path: Path) -> None:
    """Regenerate openapi.json into a tmp dir and compare bytes with the committed one."""
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    settings = Settings(ws_token="schema-gen-placeholder")
    app = create_app(settings=settings)
    fresh = json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"
    committed = OPENAPI_PATH.read_text(encoding="utf-8")
    if fresh != committed:
        diff_path = tmp_path / "openapi.fresh.json"
        diff_path.write_text(fresh, encoding="utf-8")
        pytest.fail(
            "OpenAPI schema drifted from docs/generated/openapi.json.\n"
            f"Run `make regen-contract` to update the committed artefacts.\n"
            f"Fresh schema written to {diff_path} for inspection."
        )


@pytest.mark.contract
def test_public_api_is_status_news_trading_and_macro_only() -> None:
    """#47 removed Radar, #50 removed the GMGN lane: no market/search/token/live routes or schemas remain.

    `/api/trading/*` is one route per durable aggregate (#331), named individually rather than by prefix:
    the capital lane's one hard rule is that no browser can place, amend or cancel an order, and a prefix
    wildcard would let a fifth route join without anyone reading this line.
    """

    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    components = schema["components"]["schemas"]

    api_paths = {path for path in schema["paths"] if path.startswith("/api/")}
    assert {path for path in api_paths if not path.startswith(("/api/news/", "/api/macro/"))} == {
        "/api/bootstrap",
        "/api/status",
        "/api/trading/status",
        # One route per durable aggregate (#331). `/cases` is the replacement for the retired
        # `intents.cases_without_intents`, not a second synonym beside it.
        "/api/trading/cases",
        "/api/trading/intents",
        # The admission ledger for a window of frames at once, and one Source at a time.
        "/api/trading/gate",
        "/api/trading/gate/{event_id}",
    }
    # Reads only. `trading` has three operator mutations and every one of them stays on the CLI, where it
    # runs as `workers` — `tracefold_serve` carries `default_transaction_read_only = on` precisely so the
    # internet-facing role cannot reach them.
    for path in (
        "/api/trading/status",
        "/api/trading/cases",
        "/api/trading/intents",
        "/api/trading/gate",
        "/api/trading/gate/{event_id}",
    ):
        assert set(schema["paths"][path]) == {"get"}, path
    for retired in (
        "/api/token-radar",
        "/api/stocks-radar",
        "/api/recent",
        "/api/events/by-ids",
        "/api/search",
        "/api/search/inspect",
        "/api/token-case",
        "/api/target-posts",
        "/api/target-social-timeline",
        "/api/live-market",
    ):
        assert retired not in schema["paths"], retired
    assert all(
        not name.startswith(("TokenRadar", "StocksRadar", "LiveMarket", "Search", "TokenCase", "Provider"))
        for name in components
    ), sorted(components)
    assert set(components["StatusData"]["properties"]) == {"measured_at_ms", "runtime"}
    assert set(components["BootstrapData"]["properties"]) == {"ws_token"}


@pytest.mark.contract
def test_news_routes_publish_exact_named_data_contracts() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    expected = {
        "/api/news/feed": ("get", "ApiEnvelope_NewsFeedData_"),
        "/api/news/events/{event_id}": ("get", "ApiEnvelope_NewsEventDetailData_"),
        "/api/news/status": ("get", "ApiEnvelope_NewsStatusData_"),
        # #88: current quotes and 命中复盘 are separate response types on purpose — a current rolling change
        # and a fixed post-Event return must never arrive in a field the browser could mistake for the other.
        "/api/news/quotes": ("get", "ApiEnvelope_NewsQuotesData_"),
        # #207 PR-W1: identity only. The token page's Events, price and rank window each keep their own
        # endpoint, so nothing here is a second answer to a question one of them already answers.
        "/api/news/symbols/{base}": ("get", "ApiEnvelope_NewsSymbolData_"),
    }

    assert {path for path in schema["paths"] if path.startswith("/api/news/")} == set(expected)

    for path, (method, envelope) in expected.items():
        operation = schema["paths"][path]
        assert set(operation) == {method}
        response_schema = operation[method]["responses"]["200"]["content"]["application/json"]["schema"]
        assert response_schema == {"$ref": f"#/components/schemas/{envelope}"}

    event_responses = schema["paths"]["/api/news/events/{event_id}"]["get"]["responses"]
    assert event_responses["410"]["content"]["application/json"]["schema"] == {
        "$ref": "#/components/schemas/ApiEnvelope_NewsEventDetailData_"
    }

    components = schema["components"]["schemas"]
    for name in (
        "NewsFeedData",
        "NewsFeedEventData",
        "NewsEventData",
        "NewsEventDetailData",
        "NewsEventMemberData",
        "NewsVerdictData",
        "NewsPresentationVerdictData",
        "NewsModelEditorialData",
        "NewsTradeRelevanceData",
        "NewsDeliveryData",
        "NewsStatusData",
        "NewsIngestStatusData",
        "NewsBrokerStatusData",
        "NewsPipelineStatusData",
        "NewsSourceContractStageCountsData",
        "NewsSourceContracts24hData",
        "NewsDeliveryStatusData",
        "NewsDuplicatesWithheld24hData",
        "NewsLearningRetentionStatusData",
        "NewsFeedOiData",
        "NewsOiStatusData",
        "NewsOiPolicyData",
        "NewsOiWindowSymbolData",
        "NewsOutcomeData",
        "NewsTimelineStepData",
        "NewsHealthData",
        "NewsFunnelData",
        "NewsReasonCountData",
        "NewsFeedCountsData",
        "NewsFeedSearchData",
    ):
        assert components[name]["additionalProperties"] is False

    assert set(components["NewsFeedData"]["properties"]) == {
        "events",
        "next_cursor",
        "counts",
        "filters",
        "search",
    }
    assert set(components["NewsFeedCountsData"]["properties"]) == {"total", "pushed", "held", "pending"}
    assert set(components["NewsFeedSearchData"]["properties"]) == {
        "mode",
        "normalized_query",
        "resolved_symbols",
    }
    assert set(components["NewsEventDetailData"]["properties"]) == {
        "event",
        "outcome",
        "triage",
        "timeline",
        "members",
        "verdicts",
        "deliveries",
        "review",
        "evidence_snapshots",
        "reader_receipt",
        "normalization",
        # #88: the event-level aggregate and every per-asset Reaction with the closes behind it.
        "reaction",
        "reactions",
    }
    assert set(components["NewsOutcomeData"]["properties"]) == {"kind", "text_zh", "reason_zh", "group"}
    assert set(components["NewsStatusData"]["properties"]) == {
        "state",
        "workers_state",
        "health",
        "funnel_24h",
        "reasons_24h",
        "ingest",
        "broker",
        "pipeline",
        # #207: the deterministic OI lane, whose gate names live in the judge's trace rather than in
        # `pipeline.dropped_by_rule`.
        "oi",
        "delivery",
        "learning_retention",
        "watchlist",
        "instruments",
        # #88 §11: per-source quote freshness and Reaction backlog.
        "price",
        "measured_at_ms",
    }
    assert set(components["NewsOiStatusData"]["properties"]) == {
        "policy",
        "by_rule_24h",
        "window_occupancy",
    }
    # The News gates only (#331). The capital lane's thresholds are no longer republished here; a Case's
    # own frozen checks are the only thing a reader may compare it against.
    assert "NewsOiTradeFloorsData" not in components
    assert set(components["NewsOiPolicyData"]["properties"]) == {
        "window_ms",
        "max_rank_in_window",
        "whale_oi_ratio_above_bps",
        "oi_change_at_least_bps",
    }
    state = components["NewsStatusData"]["properties"]["state"]
    assert state["enum"] == ["ready", "degraded", "warming", "unavailable"]


@pytest.mark.contract
def test_news_contract_hard_cuts_story_brief_rss_and_title_translation_surfaces() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    components = schema["components"]["schemas"]

    news_components = {name for name in components if "News" in name}
    retired_markers = ("Story", "Brief", "Rss", "Source", "TitleTranslation", "TitlePresentation", "Notification")
    source_contract_components = {
        "NewsSourceContractStageCountsData",
        "NewsSourceContracts24hData",
    }
    assert not {
        name
        for name in news_components - source_contract_components
        if any(marker in name for marker in retired_markers)
    }
    for path in ("/api/news/stories/{story_id}", "/api/news/brief", "/api/news/sources", "/api/radar"):
        assert path not in schema["paths"]

    event_properties = components["NewsEventData"]["properties"]
    assert {"story_id", "title_translation", "notification", "push_delivery_state"}.isdisjoint(event_properties)
    assert {
        "event_id",
        "event_kind",
        "source_contract_reason",
        "leader_title",
        "admission",
        "storyline_key",
    } <= set(event_properties)
    assert {"priority", "family", "dedupe_family"}.isdisjoint(event_properties)


@pytest.mark.contract
def test_news_feed_contract_exposes_bounded_event_filters() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    operation = schema["paths"]["/api/news/feed"]["get"]
    parameters = {parameter["name"]: parameter for parameter in operation["parameters"]}

    assert set(parameters) == {
        "event_family",
        "change_state",
        "assertion_status",
        "source_authority",
        "subject_code",
        "final_decision",
        "event_kind",
        "admission",
        "symbol",
        "q",
        "limit",
        "cursor",
        "outcome",
        "hours",
        # #207: which gate the deterministic OI judge applied. `final_decision` collapses a threshold withhold and
        # an unparseable provider frame into one `drop`, so the monitor's tabs cannot be built from it.
        "oi",
        "direction",
    }
    assert parameters["q"]["schema"]["maxLength"] == 200
    assert parameters["symbol"]["schema"]["maxLength"] == 32
    assert parameters["outcome"]["schema"]["pattern"] == "^(pushed|held|pending)?$"
    assert parameters["hours"]["schema"]["maximum"] == 168
    assert parameters["oi"]["schema"]["maxLength"] == 40
    limit = parameters["limit"]["schema"]
    assert limit == {"default": 50, "maximum": 100, "minimum": 1, "title": "Limit", "type": "integer"}
    assert {"reporting_origin", "provider_score_gt"}.isdisjoint(parameters)
    filters = schema["components"]["schemas"]["NewsFeedFiltersData"]
    assert set(filters["properties"]) == {
        "event_family",
        "change_state",
        "assertion_status",
        "source_authority",
        "subject_code",
        "final_decision",
        "event_kind",
        "admission",
        "symbol",
        "q",
        "limit",
        "outcome",
        "hours",
        "oi",
        "direction",
    }
    assert set(filters["required"]) == {"limit"}
    triage = schema["components"]["schemas"]["NewsTriageSummaryData"]["properties"]
    assert {"taxonomy", "relevance", "headline_zh", "final_decision"} <= set(triage)
    assert {
        "event_type",
        "event_type_zh",
        "actionable",
        "model_decision",
        "model_decision_zh",
        "title_zh",
    }.isdisjoint(triage)
    verdict = schema["components"]["schemas"]["NewsVerdictData"]["properties"]
    assert {"judgment_contract_version", "judgment_origin", "judgment_sha256", "model_editorial"} <= set(verdict)
    assert {"editorial", "trace", "prompt_version", "model_decision"}.isdisjoint(verdict)
    assert {
        "judgment_contract_version",
        "judgment_origin",
        "judgment_sha256",
        "verdict",
        "program_version",
        "program_sha256",
        "evidence_version",
        "evidence_sha256",
        "focus_fact_id",
    } <= set(schema["components"]["schemas"]["NewsVerdictData"]["required"])
    assert schema["components"]["schemas"]["NewsEvidenceSnapshotData"]["properties"]["provenance"]["const"] == (
        "observed"
    )
    assert "snapshot" not in schema["components"]["schemas"]["NewsEvidenceSnapshotData"]["properties"]
    assert "legacy_label" not in str(
        schema["components"]["schemas"]["NewsAcceptedReviewData"]["properties"]["subject_kind"]
    )
    review = schema["components"]["schemas"]["NewsAcceptedReviewData"]["properties"]
    assert {"payload", "dimensions", "novelty"}.isdisjoint(review)


@pytest.mark.contract
def test_generated_contracts_have_no_retired_product_ai_surface() -> None:
    openapi_text = OPENAPI_PATH.read_text(encoding="utf-8")
    openapi_ts_text = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    retired_contract_tokens = {
        "AgentExecutionStatusData",
        "AgentExecutionUnavailableData",
        "NewsSignalEnvelope",
        "NewsSignalSummary",
        "NarrativeAdmissionData",
        "OpsAgentExecutionData",
        "agent_admission",
        "agent_brief",
        "agent_execution",
        "macro_event_flow",
        "narrative_admission",
        "semantic_catalyst",
        "token_impacts",
    }

    for token in retired_contract_tokens:
        assert token not in openapi_text
        assert token not in openapi_ts_text


def test_contracts_md_lists_the_same_trade_channels_as_the_code() -> None:
    """`docs/CONTRACTS.md` is the hand-written public-surface truth CLAUDE.md points readers at.

    It spells the channel enum out in prose, so nothing else notices when the code-owned order gains a value:
    #173 added `product_progress` and the doc kept listing eleven codes until a reviewer read both. A client
    validating a current accepted-review payload against the stale list rejects a legitimate channel.
    """

    from tracefold.news.program.contracts import TRADE_CHANNEL_ORDER

    document = (Path(__file__).resolve().parents[2] / "docs" / "CONTRACTS.md").read_text(encoding="utf-8")
    documented = "|".join(TRADE_CHANNEL_ORDER)
    assert f"`{documented}`" in document, (
        f"docs/CONTRACTS.md does not spell the current code-owned channel order; expected the literal `{documented}`"
    )
