# tests/contract/test_openapi_drift.py
"""Contract test: regenerate OpenAPI + frontend types and assert no drift.

If this test fails, run `make regen-contract` to update the committed artefacts,
then commit the resulting diff so reviewers can see the schema change.

Note on types layout
--------------------
web/src/lib/types/openapi.ts  — auto-generated by openapi-typescript; only
                                OpenAPI path/component/operation interfaces live here.
web/src/api/types.ts          — temporary hand-authored domain types until the
                                frontend facade moves fully to generated contracts.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "docs" / "generated" / "openapi.json"
OPENAPI_TS_PATH = ROOT / "web" / "src" / "lib" / "types" / "openapi.ts"
FRONTEND_CONTRACTS_PATH = ROOT / "web" / "src" / "lib" / "types" / "frontend-contracts.ts"


@pytest.mark.contract
def test_openapi_json_matches_committed_artefact(tmp_path: Path) -> None:
    """Regenerate openapi.json into a tmp dir and compare bytes with the committed one."""
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.settings import Settings

    settings = Settings(ws_token="schema-gen-placeholder")
    app = create_app(settings=settings)
    fresh = json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"
    committed = OPENAPI_PATH.read_text(encoding="utf-8")
    if fresh != committed:
        diff_path = tmp_path / "openapi.fresh.json"
        diff_path.write_text(fresh, encoding="utf-8")
        pytest.fail(
            "OpenAPI schema drifted from docs/generated/openapi.json.\n"
            f"Run `make regen-contract` to update the committed artefacts.\n"
            f"Fresh schema written to {diff_path} for inspection."
        )


@pytest.mark.contract
def test_openapi_ts_matches_committed_artefact(tmp_path: Path) -> None:
    """Regenerate web/src/lib/types/openapi.ts and compare with the committed one."""
    fresh_path = tmp_path / "openapi.ts"
    result = subprocess.run(
        [
            "npx",
            "openapi-typescript",
            str(OPENAPI_PATH),
            "-o",
            str(fresh_path),
        ],
        cwd=str(ROOT / "web"),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.fail(
            "openapi-typescript invocation failed.\n"
            f"stdout: {result.stdout}\n"
            f"stderr: {result.stderr}\n"
            "Make sure `cd web && npm install` has run."
        )
    fresh = fresh_path.read_text(encoding="utf-8")
    committed = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    if fresh != committed:
        pytest.fail(
            f"Frontend OpenAPI types drifted from {OPENAPI_TS_PATH.relative_to(ROOT)}.\n"
            "Run `make regen-contract` to update the committed artefacts."
        )


@pytest.mark.contract
def test_news_routes_publish_exact_named_data_contracts() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.settings import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    expected = {
        "/api/news/feed": "ApiEnvelope_NewsFeedData_",
        "/api/news/stories/{story_id}": "ApiEnvelope_NewsStoryDetailData_",
        "/api/news/brief": "ApiEnvelope_NewsBriefData_",
        "/api/news/sources": "ApiEnvelope_NewsSourcesData_",
        "/api/news/status": "ApiEnvelope_NewsStatusData_",
    }

    assert {path for path in schema["paths"] if path.startswith("/api/news/")} == set(expected)

    for path, envelope in expected.items():
        response_schema = schema["paths"][path]["get"]["responses"]["200"]["content"]["application/json"]["schema"]
        assert response_schema == {"$ref": f"#/components/schemas/{envelope}"}

    for name in (
        "NewsFeedData",
        "NewsStoryData",
        "NewsStoryDetailData",
        "NewsProviderMetadataData",
        "NewsBriefData",
        "NewsSourcesData",
        "NewsStatusData",
    ):
        assert schema["components"]["schemas"][name]["additionalProperties"] is False


@pytest.mark.contract
def test_news_contract_hard_cuts_title_translation_and_old_brief_aggregates() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.settings import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    components = schema["components"]["schemas"]
    story_properties = components["NewsStoryData"]["properties"]
    brief_properties = components["NewsBriefData"]["properties"]
    publication_properties = components["NewsBriefPublicationData"]["properties"]
    status_layers = components["NewsStatusLayersData"]["properties"]

    assert "title_translation" not in story_properties
    assert not {name for name in components if "TitleTranslation" in name}
    assert set(brief_properties) == {
        "state",
        "target_fingerprint",
        "pending_due_at_ms",
        "publication",
        "latest_run",
    }
    assert {"top_stories", "brief_kind", "world_brief", "source_age_range", "provenance"} <= set(publication_properties)
    assert {"history", "candidate_story_count", "candidate_source_count", "lead", "lines"}.isdisjoint(
        brief_properties | publication_properties
    )
    assert "translation" not in status_layers


@pytest.mark.contract
def test_news_feed_contract_exposes_priority_search_and_reporting_origin_facets() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.settings import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    operation = schema["paths"]["/api/news/feed"]["get"]
    parameters = {parameter["name"]: parameter for parameter in operation["parameters"]}

    assert {"q", "reporting_origin", "provider_score_gt"}.issubset(parameters)
    assert parameters["q"]["schema"]["maxLength"] == 200
    assert parameters["reporting_origin"]["schema"]["maxLength"] == 128
    assert set(schema["components"]["schemas"]["NewsFeedFiltersData"]["required"]) >= {
        "q",
        "reporting_origin",
        "provider_score_gt",
    }
    assert set(schema["components"]["schemas"]["NewsFeedFacetsData"]["required"]) >= {"reporting_origins"}
    assert set(schema["components"]["schemas"]["NewsFeedFacetsPageData"]["required"]) >= {"reporting_origins_has_more"}


@pytest.mark.contract
def test_generated_contracts_have_no_retired_product_ai_surface() -> None:
    openapi_text = OPENAPI_PATH.read_text(encoding="utf-8")
    openapi_ts_text = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    retired_contract_tokens = {
        "AgentExecutionStatusData",
        "AgentExecutionUnavailableData",
        "NewsSignalEnvelope",
        "NewsSignalSummary",
        "NarrativeAdmissionData",
        "OpsAgentExecutionData",
        "agent_admission",
        "agent_brief",
        "agent_execution",
        "macro_event_flow",
        "narrative_admission",
        "semantic_catalyst",
        "token_impacts",
    }

    for token in retired_contract_tokens:
        assert token not in openapi_text
        assert token not in openapi_ts_text


@pytest.mark.contract
def test_market_candles_contract_has_no_legacy_market_payload_field() -> None:
    """Search and timeline contracts expose market_candles only."""
    openapi_text = OPENAPI_PATH.read_text(encoding="utf-8")
    openapi_ts_text = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    frontend_contracts_text = FRONTEND_CONTRACTS_PATH.read_text(encoding="utf-8")
    legacy_field = "market_overlay"

    assert "market_candles" in openapi_text
    assert "market_candles" in openapi_ts_text
    assert "market_candles" in frontend_contracts_text
    assert legacy_field not in openapi_text
    assert legacy_field not in openapi_ts_text
    assert legacy_field not in frontend_contracts_text
