# tests/contract/test_openapi_drift.py
"""Contract test: regenerate OpenAPI + frontend types and assert no drift.

If this test fails, run `make regen-contract` to update the committed artefacts,
then commit the resulting diff so reviewers can see the schema change.

Note on types layout
--------------------
web/src/lib/types/openapi.ts            — auto-generated by openapi-typescript; only
                                          OpenAPI path/component/operation interfaces
                                          live here.
web/src/lib/types/frontend-contracts.ts — the hand-authored `ApiResponse` envelope and
                                          the aliases the console reads the generated
                                          schemas through.
web/src/lib/types/index.ts              — the barrel both of the above are imported from.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "docs" / "generated" / "openapi.json"
OPENAPI_TS_PATH = ROOT / "web" / "src" / "lib" / "types" / "openapi.ts"


@pytest.mark.contract
def test_openapi_json_matches_committed_artefact(tmp_path: Path) -> None:
    """Regenerate openapi.json into a tmp dir and compare bytes with the committed one."""
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    settings = Settings(ws_token="schema-gen-placeholder")
    app = create_app(settings=settings)
    fresh = json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"
    committed = OPENAPI_PATH.read_text(encoding="utf-8")
    if fresh != committed:
        diff_path = tmp_path / "openapi.fresh.json"
        diff_path.write_text(fresh, encoding="utf-8")
        pytest.fail(
            "OpenAPI schema drifted from docs/generated/openapi.json.\n"
            f"Run `make regen-contract` to update the committed artefacts.\n"
            f"Fresh schema written to {diff_path} for inspection."
        )


@pytest.mark.contract
def test_public_api_is_status_news_trading_and_macro_only() -> None:
    """#47 removed Radar, #50 removed the GMGN lane: no market/search/token/live routes or schemas remain.

    `/api/trading/*` is an exact read-only allowlist, named individually rather than by prefix.
    The browser has no manual command or order authority (#624).
    """

    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    components = schema["components"]["schemas"]

    api_paths = {path for path in schema["paths"] if path.startswith("/api/")}
    assert {path for path in api_paths if not path.startswith(("/api/news/", "/api/macro/"))} == {
        "/api/bootstrap",
        "/api/status",
        "/api/trading/status",
        # One route per question the desk asks. `/api/trading/signals` and the two raw
        # `/api/trading/execution/*` projections were three more shapes over the same ledgers the
        # desk reads already folded, and nothing in the browser called any of them (#537 PR-5).
        "/api/trading/cases",
        "/api/trading/scoreboard",
        # #528 PR-1: the desk table. One row per entry folded from the Runtime's own observations,
        # with account-wide realized totals; it appends nothing.
        "/api/trading/executions",
    }
    # The public surface and the Serve database pool are read-only (#624).
    for path in api_paths:
        assert set(schema["paths"][path]) == {"get"}, path
    assert "/api/trading/execution/commands" not in schema["paths"]
    for retired in (
        "/api/token-radar",
        "/api/stocks-radar",
        "/api/recent",
        "/api/events/by-ids",
        "/api/search",
        "/api/search/inspect",
        "/api/token-case",
        "/api/target-posts",
        "/api/target-social-timeline",
        "/api/live-market",
        # #589 PR-2. The admission ledger kept its two HTTP shapes for a browser reader #553 PR-1 had
        # already deleted; `tracefold trading gate` reads the same two statements directly.
        "/api/trading/gate",
        "/api/trading/gate/{event_id}",
    ):
        assert retired not in schema["paths"], retired
    assert all(not name.startswith("TradingGate") for name in components), sorted(components)
    assert all(
        not name.startswith(("TokenRadar", "StocksRadar", "LiveMarket", "Search", "TokenCase", "Provider"))
        for name in components
    ), sorted(components)
    assert set(components["StatusData"]["properties"]) == {"measured_at_ms", "runtime"}
    assert set(components["BootstrapData"]["properties"]) == {"ws_token"}


@pytest.mark.contract
def test_news_routes_publish_exact_named_data_contracts() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    expected = {
        "/api/news/feed": ("get", "ApiEnvelope_NewsFeedData_"),
        "/api/news/events/{event_id}": ("get", "ApiEnvelope_NewsEventDetailData_"),
        "/api/news/items/{item_id}/events": ("get", "ApiEnvelope_NewsItemRelatedEventsData_"),
        "/api/news/status": ("get", "ApiEnvelope_NewsStatusData_"),
        # #88: current quotes and 命中复盘 are separate response types on purpose — a current rolling change
        # and a fixed post-Event return must never arrive in a field the browser could mistake for the other.
        "/api/news/quotes": ("get", "ApiEnvelope_NewsQuotesData_"),
        # #207 PR-W1: identity only. The token page's Events, price and rank window each keep their own
        # endpoint, so nothing here is a second answer to a question one of them already answers.
        "/api/news/symbols/{base}": ("get", "ApiEnvelope_NewsSymbolData_"),
        # #553: market observations are stored facts and this is where they are read. The collapsed
        # list and one Item in full are separate response types because neither answer contains the
        # other — the list carries a group's newest member, the Item carries its whole timeline.
        "/api/news/market": ("get", "ApiEnvelope_NewsMarketData_"),
        "/api/news/market/{item_id}": ("get", "ApiEnvelope_NewsMarketItemData_"),
        # #572 PR-3: the wallet tape's own state. Two response types for the same reason the market
        # pair has two — the header read answers "who is followed and where is the tape", the card
        # read answers "what did the rules open and what was it worth after", and neither contains
        # the other.
        "/api/news/wallets": ("get", "ApiEnvelope_NewsWalletsData_"),
        "/api/news/wallets/events": ("get", "ApiEnvelope_NewsWalletEventsData_"),
        "/api/news/wallets/events/{episode_id}": ("get", "ApiEnvelope_NewsWalletEventDetailData_"),
    }

    assert {path for path in schema["paths"] if path.startswith("/api/news/")} == set(expected)

    for path, (method, envelope) in expected.items():
        operation = schema["paths"][path]
        assert set(operation) == {method}
        response_schema = operation[method]["responses"]["200"]["content"]["application/json"]["schema"]
        assert response_schema == {"$ref": f"#/components/schemas/{envelope}"}

    event_responses = schema["paths"]["/api/news/events/{event_id}"]["get"]["responses"]
    assert set(event_responses) == {"200", "404", "422"}
    assert event_responses["404"]["content"]["application/json"]["schema"] == {
        "$ref": "#/components/schemas/ApiEnvelope_NewsEventDetailData_"
    }
    market_item_responses = schema["paths"]["/api/news/market/{item_id}"]["get"]["responses"]
    assert set(market_item_responses) == {"200", "404", "422"}
    assert market_item_responses["404"]["content"]["application/json"]["schema"] == {
        "$ref": "#/components/schemas/ApiEnvelope_NewsMarketItemData_"
    }

    components = schema["components"]["schemas"]
    for name in (
        "NewsFeedData",
        "NewsFeedEventData",
        "NewsEventData",
        "NewsEventDetailData",
        "NewsEventMemberData",
        "NewsDeliveryData",
        "NewsStatusData",
        "NewsIngestStatusData",
        "NewsBrokerStatusData",
        "NewsPipelineStatusData",
        "NewsSourceContractStageCountsData",
        "NewsSourceContracts24hData",
        "NewsDeliveryStatusData",
        "NewsDuplicatesWithheld24hData",
        "NewsMarketData",
        "NewsMarketDeliveryData",
        "NewsMarketFiltersData",
        "NewsMarketGroupData",
        "NewsMarketItemData",
        "NewsMarketObservationData",
        "NewsMarketSourceData",
        "NewsOutcomeData",
        "NewsTimelineStepData",
        "NewsHealthData",
        "NewsFunnelData",
        "NewsReasonCountData",
        "NewsFeedCountsData",
        "NewsFeedSearchData",
    ):
        assert components[name]["additionalProperties"] is False

    assert set(components["NewsFeedData"]["properties"]) == {
        "events",
        "next_cursor",
        "counts",
        "filters",
        "search",
    }
    assert set(components["NewsFeedCountsData"]["properties"]) == {"total", "pushed", "held", "pending"}
    assert set(components["NewsFeedSearchData"]["properties"]) == {
        "mode",
        "normalized_query",
        "resolved_symbols",
    }
    assert set(components["NewsEventDetailData"]["properties"]) == {
        "event",
        "outcome",
        "event_update",
        "processing",
        "timeline",
        "members",
        "deliveries",
        "evidence_snapshots",
        "reader_receipt",
        "normalization",
        # #88: the event-level aggregate and every per-asset Reaction with the closes behind it.
    }
    assert set(components["NewsOutcomeData"]["properties"]) == {"kind", "text_zh", "reason_zh", "group"}
    assert set(components["NewsStatusData"]["properties"]) == {
        "state",
        "workers_state",
        "health",
        "funnel_24h",
        "primary_asset_markets_24h",
        "reasons_24h",
        "ingest",
        "broker",
        "pipeline",
        "delivery",
        "watchlist",
        "instruments",
        # #88 §11: per-source quote freshness and Reaction backlog.
        "price",
        "measured_at_ms",
    }
    # No OI-shaped response type is left anywhere. #331 removed the capital lane's floors — a Case's
    # own frozen checks are the only thing a reader may compare it against — #458 removed the News push
    # gates themselves, and #553 removed the lane: an OI observation is a market fact with its own
    # surface, not an Event with a status section beside the editorial pipeline's.
    for retired in ("NewsOiStatusData", "NewsFeedOiData", "NewsOiTradeFloorsData", "NewsOiPolicyData"):
        assert retired not in components, retired
    assert "NewsOiWindowSymbolData" not in components
    assert set(components["NewsMarketData"]["properties"]) == {
        "groups",
        "next_cursor",
        "sources",
        "filters",
        # A page scans a bounded number of rows. When it fills that bound a run's `observation_count`
        # is a floor, and the client is told rather than shown a number that stopped counting.
        "scan_truncated",
    }
    assert set(components["NewsMarketItemData"]["properties"]) == {
        "observation",
        "provider_params",
        "description",
        "raw_first_line",
        "notification_status",
        "notification_reason",
        # #553 PR-2: the card that spoke for this observation, and the observations it covered.
        "notification_delivery",
        "notification_covered_item_ids",
        "timeline",
    }
    # #553 PR-2 is a hard cut: the placeholder that said "no loop is wired" is gone from both payloads
    # rather than left publishing a constant `false`.
    for payload in ("NewsMarketData", "NewsMarketItemData"):
        assert "notifications_connected" not in components[payload]["properties"], payload
    # One card: what it covered, what was attempted, what came back. The receipt itself is never
    # published -- only which provider answered -- because a receipt carries channel identifiers and
    # the console's question is whether a reader was told, not how to address the message.
    assert set(components["NewsMarketDeliveryData"]["properties"]) == {
        "delivery_key",
        "trigger_reason",
        "trigger_item_id",
        "state",
        "attempts",
        "covered_count",
        "covered_from_ms",
        "covered_to_ms",
        "card",
        "error",
        "receipt_provider",
        "first_attempt_at_ms",
        "last_attempt_at_ms",
        "next_attempt_at_ms",
        "settled_at_ms",
    }
    assert "receipt" not in components["NewsMarketDeliveryData"]["properties"]
    assert components["NewsMarketDeliveryData"]["properties"]["state"]["enum"] == [
        "pending",
        "sending",
        "sent",
        "failed",
        "unknown",
        "unavailable",
    ]
    assert set(components["NewsMarketFiltersData"]["properties"]) == {
        "kind",
        "from_ms",
        "to_ms",
        "limit",
        "asset",
        "provider",
        "venue",
        "measurement_definition",
        "sort",
    }
    # Two independent pairs, on the group and on the Item alike: what the parser proved, and what the
    # sender did. A client cannot derive either from the other, which is why neither is folded away.
    assert {"parse_status", "parse_error"} <= set(components["NewsMarketObservationData"]["properties"])
    assert {"notification_status", "notification_reason"} <= set(components["NewsMarketGroupData"]["required"])
    assert {"notification_status", "notification_reason"} <= set(components["NewsMarketObservationData"]["required"])
    # Which notification group the loop assigned the observation to, and which card spoke for it.
    # Deliberately not the display `group_key`: a smart-money account changing action breaks the
    # display run and must not break the notification group, because that change is the news.
    assert {"notify_group_key", "delivery_key"} <= set(components["NewsMarketObservationData"]["properties"])
    # What arrived, and what a reader was told about it, in one per-kind block.
    assert {"received", "parsed", "raw", "groups", "merged", "sent", "failed", "unknown"} <= set(
        components["NewsMarketSourceData"]["properties"]
    )
    # Where the next page starts. Paging from `latest` would re-scan the rest of the run.
    assert {"oldest_received_at_ms", "oldest_item_id"} <= set(components["NewsMarketGroupData"]["properties"])
    assert components["NewsMarketObservationData"]["properties"]["market_kind"]["enum"] == [
        "oi",
        "liquidation",
        "smart_money",
        "unknown_market",
        # #572 PR-2: derived by this process from chain logs rather than reported by a provider, and an
        # ordinary market observation in every other respect.
        "wallet",
    ]
    # Provider decimals cross the wire as their exact stored text; a JSON number would round a notional
    # the ledger holds precisely.
    for money in ("notional_usd", "price", "pnl_usd"):
        assert components["NewsMarketObservationData"]["properties"][money]["anyOf"][0] == {"type": "string"}, money
    state = components["NewsStatusData"]["properties"]["state"]
    assert state["enum"] == ["ready", "degraded", "warming", "unavailable"]


@pytest.mark.contract
def test_news_contract_hard_cuts_story_brief_rss_and_title_translation_surfaces() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    components = schema["components"]["schemas"]

    news_components = {name for name in components if "News" in name}
    retired_markers = ("Story", "Brief", "Rss", "Source", "TitleTranslation", "TitlePresentation", "Notification")
    # `Source` is a retired-RSS marker, so every current name carrying it is listed here by hand: the
    # two source-contract funnel counts, and #553's per-kind market intake summary. A new `News*Source*`
    # type has to be added deliberately, which is the point.
    named_source_components = {
        "NewsSourceContractStageCountsData",
        "NewsSourceContracts24hData",
        "NewsMarketSourceData",
        # #706: the provenance of one piece of evidence an adopted EventUpdate cites.
        "NewsUpdateSourceData",
    }
    # #706: the notification planner's claim decisions and its work state are a current contract, named
    # deliberately rather than admitted by the retired marker.
    named_notification_components = {"NewsNotificationPlanData", "NewsNotificationWorkData"}
    assert not {
        name
        for name in news_components - named_source_components - named_notification_components
        if any(marker in name for marker in retired_markers)
    }
    for path in ("/api/news/stories/{story_id}", "/api/news/brief", "/api/news/sources", "/api/radar"):
        assert path not in schema["paths"]

    event_properties = components["NewsEventData"]["properties"]
    assert {"story_id", "title_translation", "notification", "push_delivery_state"}.isdisjoint(event_properties)
    assert {
        "event_id",
        "event_kind",
        "leader_title",
        "admission",
        "storyline_key",
    } <= set(event_properties)
    # #553: `source_contract_reason` named why a market frame was refused an Event. Market frames are
    # stored as facts now rather than refused, so the field could only ever have been null.
    assert {"priority", "family", "dedupe_family", "source_contract_reason"}.isdisjoint(event_properties)
    assert components["NewsEventData"]["properties"]["event_kind"]["enum"] == ["news", "listing"]


@pytest.mark.contract
def test_news_feed_contract_exposes_current_bounded_filters() -> None:
    from tracefold.app.http.app import create_app
    from tracefold.platform.config.models import Settings

    schema = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()
    parameters = {parameter["name"]: parameter for parameter in schema["paths"]["/api/news/feed"]["get"]["parameters"]}
    assert set(parameters) == {
        "source_authority",
        "subject_code",
        "event_kind",
        "admission",
        "symbol",
        "q",
        "limit",
        "cursor",
        "outcome",
        "hours",
    }
    assert parameters["limit"]["schema"]["maximum"] == 100
    assert set(schema["components"]["schemas"]["NewsFeedFiltersData"]["properties"]) == set(parameters) - {"cursor"}
    feed_row = schema["components"]["schemas"]["NewsFeedEventData"]["properties"]
    assert "update" in feed_row and "legacy_verdict" not in feed_row
    detail = schema["components"]["schemas"]["NewsEventDetailData"]["properties"]
    assert "feedback" not in detail and "verdicts" not in detail
    for retired in ("NewsLegacyVerdictData", "NewsVerdictData", "NewsAcceptedReviewData"):
        assert retired not in schema["components"]["schemas"]


def test_news_event_update_contract_is_exact_and_types_the_core_vocabulary() -> None:
    """#706: the Event detail's EventUpdate and processing sections, as published.

    Each vocabulary is typed by the core contract's own `Literal`, so an enum the News Agent can write
    is one the browser contract names, and the outcome kinds are exactly the ones `event_outcome` returns.
    """

    from typing import get_args

    from tracefold.app.http.app import create_app
    from tracefold.news.notifications.contracts import ClaimReason, PlanAction
    from tracefold.news.outcome import OutcomeKind
    from tracefold.news.update_view import LegacyClaimReason
    from tracefold.news.updates.contracts import Asset, ChangeKind, ContentKind, Mode, Phase
    from tracefold.platform.config.models import Settings

    components = create_app(settings=Settings(ws_token="schema-gen-placeholder")).openapi()["components"]["schemas"]

    assert set(components["NewsEventUpdateData"]["properties"]) == {
        "update_ref",
        "content_revision",
        "input_revision",
        "previous_content_revision",
        "adopted_at_ms",
        "scope_repair_id",
        "headline",
        "headline_source",
        "topics",
        "claims",
        "retired_claim_refs",
        "disputed_claim_refs",
        "changes",
        "sources",
        "implications",
        "open_questions",
    }
    assert set(components["NewsProcessingData"]["properties"]) == {
        "semantic",
        "observations",
        "notification",
        "intents",
        "update_error_code",
    }
    claim = components["NewsClaimData"]["properties"]
    assert {
        "mode",
        "phase",
        "content_kind",
        "quantities",
        "conditions",
        "effective_at",
        "occurred_at",
        "statistical_period",
        "assets",
        "citations",
        "retired",
        "disputed",
        "relation_counts",
    } <= set(claim)
    assert claim["mode"]["enum"] == list(get_args(Mode))
    assert claim["content_kind"]["enum"] == list(get_args(ContentKind))
    assert claim["phase"]["anyOf"][0]["enum"] == list(get_args(Phase))
    assert components["NewsClaimAssetData"]["properties"]["market_type"]["enum"] == list(
        get_args(Asset.model_fields["market_type"].annotation)
    )
    assert components["NewsClaimChangeData"]["properties"]["kind"]["enum"] == list(get_args(ChangeKind))
    assert components["NewsClaimDecisionData"]["properties"]["reason"]["enum"] == [
        *get_args(ClaimReason),
        *get_args(LegacyClaimReason),
    ]
    assert components["NewsNotificationPlanData"]["properties"]["action"]["enum"] == list(get_args(PlanAction))
    assert components["NewsImplicationData"]["properties"]["origin"]["enum"] == [
        "reported_causality",
        "system_hypothesis",
    ]
    assert components["NewsOutcomeData"]["properties"]["kind"]["enum"] == list(get_args(OutcomeKind))
    assert components["NewsTimelineStepData"]["properties"]["stage"]["enum"] == [
        "received",
        "gate",
        "evidence",
        "semantic",
        "notify",
        "delivery",
    ]


# The version families #369/#398 retired. `tests/architecture/test_news_current_contract_hard_cut.py`
# banned these across five trees — `tracefold/`, `web/src`, `web/tests`, `docs/generated` and `tests/`
# — with an allowlist of historical files and no removal condition, so every migration, fixture and
# doc that legitimately mentions a retired name had to be re-declared there. The risk that outlives
# the cut is narrower and is the one below: a retired identity re-entering the *published* contract.
# Everything else is proved positively by the exact `==` property sets in the tests above.
_RETIRED_NEWS_IDENTITIES = frozenset(
    {f"news_semantic_program_v{version}" for version in range(1, 8)}
    | {f"news_program_v{version}" for version in range(1, 8)}
    | {f"news_triage_policy_v{version}" for version in range(1, 11)}
    | {f"news_delivery_card_v{version}" for version in range(1, 12)}
    | {f"news_review_v{version}" for version in range(1, 6)}
    | {
        "news_liquidation_fact_v1",
        "news_liquidation_policy_v1",
        "news_oi_signal_v1",
        "news_reader_history_v1",
        "news_reader_history_v2",
        "told_context_selector_v1",
        "told_context_selector_v2",
        "told_context_selector_v3",
    }
)


@pytest.mark.contract
def test_published_contract_names_no_retired_news_identity() -> None:
    openapi_text = OPENAPI_PATH.read_text(encoding="utf-8")
    assert sorted(token for token in _RETIRED_NEWS_IDENTITIES if token in openapi_text) == []


@pytest.mark.contract
def test_generated_contracts_have_no_retired_product_ai_surface() -> None:
    openapi_text = OPENAPI_PATH.read_text(encoding="utf-8")
    openapi_ts_text = OPENAPI_TS_PATH.read_text(encoding="utf-8")
    retired_contract_tokens = {
        "AgentExecutionStatusData",
        "AgentExecutionUnavailableData",
        "NewsSignalEnvelope",
        "NewsSignalSummary",
        "NarrativeAdmissionData",
        "OpsAgentExecutionData",
        "agent_admission",
        "agent_brief",
        "agent_execution",
        "macro_event_flow",
        "narrative_admission",
        "semantic_catalyst",
        "token_impacts",
    }

    for token in retired_contract_tokens:
        assert token not in openapi_text
        assert token not in openapi_ts_text


_CONTRACTS_MD = ROOT / "docs" / "CONTRACTS.md"
_RETIRED_BEGIN = "<!-- retired-routes:begin -->"
_RETIRED_END = "<!-- retired-routes:end -->"
# Path templates as they appear in prose. `?` and backticks are excluded so a documented query
# string stops at the path, and a field path such as `/api/news/status.price` is truncated at the
# dot to the route that publishes it.
_API_PATH_RE = re.compile(r"/api/[A-Za-z0-9_{}/*.-]*")


def _documented_api_paths(text: str) -> set[str]:
    """Literal `/api/...` route templates named in prose.

    A token carrying `*` is a family gloss (`/api/*`, `/api/token-images/*`), not a route, and is
    not a claim this test can check.
    """

    found: set[str] = set()
    for raw in _API_PATH_RE.findall(text):
        if "*" in raw:
            continue
        path = raw.split(".", 1)[0].rstrip("/")
        if path != "/api":
            found.add(path)
    return found


def test_contracts_md_names_only_live_api_paths_and_names_every_one() -> None:
    """`docs/CONTRACTS.md` may not describe a route the service does not serve, or omit one it does.

    The document is hand-written and the API is generated, so the two drift in both directions and
    neither drift is visible to a reader: #589 found it claiming "exactly seven GET route templates"
    when nine were registered. Route *shapes* are `docs/generated/openapi.json` and are not repeated
    there; what is repeated is which routes exist, and that is what this pins. Retired routes are
    exempt by being listed between the retired-routes markers, which is also where the 404 contract
    is stated, so removing a route means moving one line rather than deleting a paragraph.
    """

    document = _CONTRACTS_MD.read_text(encoding="utf-8")
    assert _RETIRED_BEGIN in document and _RETIRED_END in document, (
        f"docs/CONTRACTS.md must keep the {_RETIRED_BEGIN} / {_RETIRED_END} block naming retired routes"
    )
    retired_block = document.split(_RETIRED_BEGIN, 1)[1].split(_RETIRED_END, 1)[0]
    retired = _documented_api_paths(retired_block)
    documented = _documented_api_paths(document) - retired

    live = {path for path in json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))["paths"] if path.startswith("/api/")}

    assert live, "docs/generated/openapi.json publishes no /api path; regenerate it before reading this"
    assert not (retired & live), (
        "docs/CONTRACTS.md lists a live route as retired: "
        f"{sorted(retired & live)}. Move it out of the retired-routes block."
    )
    assert not (documented - live), (
        "docs/CONTRACTS.md describes routes that are not registered: "
        f"{sorted(documented - live)}. Delete the prose, or list the path in the retired-routes block."
    )
    assert not (live - documented), (
        "docs/CONTRACTS.md never names these live routes: "
        f"{sorted(live - documented)}. Add each to the endpoint families table."
    )
