/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Event */
        get: operations["get_news_event_api_news_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Feed */
        get: operations["get_news_feed_api_news_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Status */
        get: operations["get_news_status_api_news_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiEnvelope[BootstrapData] */
        ApiEnvelope_BootstrapData_: {
            data?: components["schemas"]["BootstrapData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NewsEventDetailData] */
        ApiEnvelope_NewsEventDetailData_: {
            data?: components["schemas"]["NewsEventDetailData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NewsFeedData] */
        ApiEnvelope_NewsFeedData_: {
            data?: components["schemas"]["NewsFeedData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NewsStatusData] */
        ApiEnvelope_NewsStatusData_: {
            data?: components["schemas"]["NewsStatusData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[StatusData] */
        ApiEnvelope_StatusData_: {
            data?: components["schemas"]["StatusData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** BootstrapData */
        BootstrapData: {
            /** Ws Token */
            ws_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewsBrokerQueueData */
        NewsBrokerQueueData: {
            /** Consumers */
            consumers: number;
            /** Messages */
            messages: number;
        };
        /** NewsBrokerStatusData */
        NewsBrokerStatusData: {
            /** Configured */
            configured: boolean;
            /** Connected */
            connected?: boolean | null;
            /** Error Code */
            error_code?: string | null;
            /** Observed At Ms */
            observed_at_ms?: number | null;
            /** Queues */
            queues?: {
                [key: string]: components["schemas"]["NewsBrokerQueueData"];
            };
        };
        /** NewsControlStateData */
        NewsControlStateData: {
            /** Mutes */
            mutes?: {
                [key: string]: unknown;
            }[];
            /**
             * Paused
             * @default false
             */
            paused: boolean;
        };
        /** NewsDeliveryData */
        NewsDeliveryData: {
            /** Attempted At Ms */
            attempted_at_ms: number;
            /** Error Code */
            error_code?: string | null;
            /** Kind */
            kind: string;
            /** Receipt */
            receipt?: {
                [key: string]: unknown;
            } | null;
            /** Settled At Ms */
            settled_at_ms?: number | null;
            /** State */
            state: string;
        };
        /** NewsDeliveryStatusData */
        NewsDeliveryStatusData: {
            /** Delivery Available */
            delivery_available: boolean;
            /** E2E P95 Ms */
            e2e_p95_ms?: number | null;
            /** Hourly Cap */
            hourly_cap: number;
            /** Last Error Code */
            last_error_code?: string | null;
            /**
             * Sent 1H
             * @default 0
             */
            sent_1h: number;
            /**
             * Sent 24H
             * @default 0
             */
            sent_24h: number;
            /**
             * Terminal 24H
             * @default 0
             */
            terminal_24h: number;
        };
        /** NewsDeliverySummaryData */
        NewsDeliverySummaryData: {
            /** Error Code */
            error_code?: string | null;
            /** Settled At Ms */
            settled_at_ms?: number | null;
            /** State */
            state: string;
        };
        /** NewsEventData */
        NewsEventData: {
            /** Admission */
            admission: string;
            /** Asset Class */
            asset_class: string;
            /**
             * Context Line
             * @default
             */
            context_line: string;
            /** Engine Type */
            engine_type: string;
            /** Event Id */
            event_id: string;
            /** Family */
            family: string;
            /** Grounded Assets */
            grounded_assets?: string[];
            /** Ingest Mode */
            ingest_mode: string;
            /** Last Member At Ms */
            last_member_at_ms: number;
            /**
             * Leader Description
             * @default
             */
            leader_description: string;
            /** Leader Title */
            leader_title: string;
            /** Leader Url */
            leader_url?: string | null;
            /**
             * Macro Lexicon
             * @default false
             */
            macro_lexicon: boolean;
            /** Member Count */
            member_count: number;
            /** Opened At Ms */
            opened_at_ms: number;
            /** Priority */
            priority: string;
            /** Provenance */
            provenance?: string[];
            /** Provider Score Max */
            provider_score_max?: number | null;
            /** Published At Ms */
            published_at_ms?: number | null;
            /**
             * Reporting Origin
             * @default
             */
            reporting_origin: string;
            /**
             * Storyline Key
             * @default
             */
            storyline_key: string;
            /** Watchlist Hits */
            watchlist_hits?: string[];
        };
        /** NewsEventDetailData */
        NewsEventDetailData: {
            /** Deliveries */
            deliveries: components["schemas"]["NewsDeliveryData"][];
            event: components["schemas"]["NewsEventData"];
            /** Labels */
            labels?: components["schemas"]["NewsLabelData"][];
            /** Members */
            members: components["schemas"]["NewsEventMemberData"][];
            outcome: components["schemas"]["NewsOutcomeData"];
            /** Timeline */
            timeline?: components["schemas"]["NewsTimelineStepData"][];
            triage?: components["schemas"]["NewsTriageSummaryData"] | null;
            /** Verdicts */
            verdicts: components["schemas"]["NewsVerdictData"][];
        };
        /** NewsEventMemberData */
        NewsEventMemberData: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Item Id */
            item_id: string;
            /** Jaccard Estimate */
            jaccard_estimate?: number | null;
            /** Joined At Ms */
            joined_at_ms: number;
            /** Match Kind */
            match_kind: string;
            /** Provenance */
            provenance?: string[];
            /** Published At Ms */
            published_at_ms: number;
            /** Reporting Origin */
            reporting_origin: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /**
         * NewsFeedCountsData
         * @description How the request's filter and window split across the three outcome groups, for the feed's task tabs.
         *
         *     ``total`` is the sum of the other three: the groups partition the feed exactly.
         */
        NewsFeedCountsData: {
            /** Held */
            held: number;
            /** Pending */
            pending: number;
            /** Pushed */
            pushed: number;
            /** Total */
            total: number;
        };
        /** NewsFeedData */
        NewsFeedData: {
            counts?: components["schemas"]["NewsFeedCountsData"] | null;
            /** Events */
            events: components["schemas"]["NewsFeedEventData"][];
            filters: components["schemas"]["NewsFeedFiltersData"];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** NewsFeedEventData */
        NewsFeedEventData: {
            /** Admission */
            admission: string;
            /** Asset Class */
            asset_class: string;
            /**
             * Context Line
             * @default
             */
            context_line: string;
            delivery?: components["schemas"]["NewsDeliverySummaryData"] | null;
            /** Engine Type */
            engine_type: string;
            /** Event Id */
            event_id: string;
            /** Family */
            family: string;
            /** Grounded Assets */
            grounded_assets?: string[];
            /** Ingest Mode */
            ingest_mode: string;
            /** Last Member At Ms */
            last_member_at_ms: number;
            /**
             * Leader Description
             * @default
             */
            leader_description: string;
            /** Leader Title */
            leader_title: string;
            /** Leader Url */
            leader_url?: string | null;
            /**
             * Macro Lexicon
             * @default false
             */
            macro_lexicon: boolean;
            /** Member Count */
            member_count: number;
            /** Opened At Ms */
            opened_at_ms: number;
            outcome: components["schemas"]["NewsOutcomeData"];
            /** Priority */
            priority: string;
            /** Provenance */
            provenance?: string[];
            /** Provider Score Max */
            provider_score_max?: number | null;
            /** Published At Ms */
            published_at_ms?: number | null;
            /**
             * Reporting Origin
             * @default
             */
            reporting_origin: string;
            /**
             * Storyline Key
             * @default
             */
            storyline_key: string;
            /** Title Zh */
            title_zh?: string | null;
            triage?: components["schemas"]["NewsTriageSummaryData"] | null;
            /** Watchlist Hits */
            watchlist_hits?: string[];
        };
        /** NewsFeedFiltersData */
        NewsFeedFiltersData: {
            /** Admission */
            admission?: string | null;
            /** Decision */
            decision?: string | null;
            /** Family */
            family?: string | null;
            /** Hours */
            hours?: number | null;
            /** Limit */
            limit: number;
            /** Outcome */
            outcome?: ("pushed" | "held" | "pending") | null;
            /** Priority */
            priority?: string | null;
            /** Q */
            q?: string | null;
            /**
             * Sort
             * @enum {string}
             */
            sort: "latest" | "priority";
            /** Symbol */
            symbol?: string | null;
        };
        /** NewsFunnelData */
        NewsFunnelData: {
            /**
             * Candidates
             * @default 0
             */
            candidates: number;
            /**
             * Decided Push
             * @default 0
             */
            decided_push: number;
            /**
             * Delivered
             * @default 0
             */
            delivered: number;
            /**
             * Delivered 1H
             * @default 0
             */
            delivered_1h: number;
            /**
             * Received
             * @default 0
             */
            received: number;
            /**
             * Received 1H
             * @default 0
             */
            received_1h: number;
            /**
             * Triaged
             * @default 0
             */
            triaged: number;
        };
        /** NewsHealthData */
        NewsHealthData: {
            broker: components["schemas"]["NewsHealthItemData"];
            delivery: components["schemas"]["NewsHealthItemData"];
            ingest: components["schemas"]["NewsHealthItemData"];
            model: components["schemas"]["NewsHealthItemData"];
            /**
             * Overall
             * @enum {string}
             */
            overall: "ok" | "warn" | "bad" | "off";
        };
        /** NewsHealthItemData */
        NewsHealthItemData: {
            /**
             * Detail Zh
             * @default
             */
            detail_zh: string;
            /**
             * Level
             * @enum {string}
             */
            level: "ok" | "warn" | "bad" | "off";
            /** Summary Zh */
            summary_zh: string;
        };
        /** NewsIncidentData */
        NewsIncidentData: {
            /** Cause Class */
            cause_class: string;
            /** Incident Id */
            incident_id: number;
            /** Opened At Ms */
            opened_at_ms: number;
            /** Planned */
            planned: boolean;
        };
        /** NewsIngestStatusData */
        NewsIngestStatusData: {
            /** Configured Strategy Ids */
            configured_strategy_ids?: string[];
            /** Connected */
            connected: boolean;
            /** Last Error Code */
            last_error_code?: string | null;
            /** Last Frame At Ms */
            last_frame_at_ms?: number | null;
            /** Last Publish At Ms */
            last_publish_at_ms?: number | null;
            /** Open Incidents */
            open_incidents?: components["schemas"]["NewsIncidentData"][];
            /** Provider Enabled Strategy Ids */
            provider_enabled_strategy_ids?: string[] | null;
            /** Strategy Warnings */
            strategy_warnings?: string[];
            /** Token Configured */
            token_configured: boolean;
        };
        /**
         * NewsInstrumentUniverse
         * @description #75: what the last venue snapshot holds. `last_snapshot_ms` is None until the first snapshot lands.
         */
        NewsInstrumentUniverse: {
            /**
             * Base Symbols
             * @default 0
             */
            base_symbols: number;
            /** By Venue */
            by_venue?: {
                [key: string]: number;
            };
            /**
             * Delisted
             * @default 0
             */
            delisted: number;
            /** Last Snapshot Ms */
            last_snapshot_ms?: number | null;
            /**
             * Trading
             * @default 0
             */
            trading: number;
            /**
             * Venues
             * @default 0
             */
            venues: number;
        };
        /** NewsLabelData */
        NewsLabelData: {
            /** Created At Ms */
            created_at_ms: number;
            /** Label */
            label?: {
                [key: string]: unknown;
            };
            /** Label Version */
            label_version: string;
            /**
             * Labeled By
             * @default operator
             */
            labeled_by: string;
            /** Source */
            source: string;
            /**
             * Subject
             * @default
             */
            subject: string;
        };
        /**
         * NewsOutcomeData
         * @description One human-readable conclusion per Event; ``kind`` is a stable enum, the texts are Chinese reader copy.
         */
        NewsOutcomeData: {
            /**
             * Group
             * @enum {string}
             */
            group: "pushed" | "held" | "pending";
            /**
             * Kind
             * @enum {string}
             */
            kind: "held_recovery" | "held_gate" | "queued_publish" | "queued_triage" | "dropped" | "throttled" | "degraded_dropped" | "pending_delivery" | "delivered" | "delivery_failed";
            /**
             * Reason Zh
             * @default
             */
            reason_zh: string;
            /** Text Zh */
            text_zh: string;
        };
        /** NewsPipelineStatusData */
        NewsPipelineStatusData: {
            /** Candidate Share 24H */
            candidate_share_24h?: number | null;
            /**
             * Candidates 24H
             * @default 0
             */
            candidates_24h: number;
            /**
             * Decided Push 24H
             * @default 0
             */
            decided_push_24h: number;
            /** Dropped By Rule */
            dropped_by_rule?: {
                [key: string]: number;
            };
            /**
             * Events 1H
             * @default 0
             */
            events_1h: number;
            /**
             * Events 24H
             * @default 0
             */
            events_24h: number;
            /**
             * Labeled Missed 24H
             * @default 0
             */
            labeled_missed_24h: number;
            /**
             * Labeled Missed Without Event 24H
             * @default 0
             */
            labeled_missed_without_event_24h: number;
            /**
             * Novelty Defaulted 24H
             * @default 0
             */
            novelty_defaulted_24h: number;
            /** Pushed By Rule */
            pushed_by_rule?: {
                [key: string]: number;
            };
            /** Queue Lag P95 Ms */
            queue_lag_p95_ms?: number | null;
            /**
             * Reasked 24H
             * @default 0
             */
            reasked_24h: number;
            /** Suppressed By Reason */
            suppressed_by_reason?: {
                [key: string]: number;
            };
            /**
             * Throttled 24H
             * @default 0
             */
            throttled_24h: number;
            /** Throttled By Key */
            throttled_by_key?: {
                [key: string]: number;
            };
            /**
             * Triage 24H
             * @default 0
             */
            triage_24h: number;
            /**
             * Triage Degraded 24H
             * @default 0
             */
            triage_degraded_24h: number;
            /** Triage Degraded By Code 24H */
            triage_degraded_by_code_24h?: {
                [key: string]: number;
            };
            /** Triage Fallback Model */
            triage_fallback_model?: string | null;
            /** Triage Model */
            triage_model?: string | null;
            /** Triage P50 Ms */
            triage_p50_ms?: number | null;
            /** Triage P95 Ms */
            triage_p95_ms?: number | null;
        };
        /** NewsReasonCountData */
        NewsReasonCountData: {
            /** Count */
            count: number;
            /** Key */
            key: string;
            /** Label Zh */
            label_zh: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "gate" | "drop" | "throttle" | "push" | "degraded";
        };
        /** NewsStatusData */
        NewsStatusData: {
            broker: components["schemas"]["NewsBrokerStatusData"];
            control: components["schemas"]["NewsControlStateData"];
            delivery: components["schemas"]["NewsDeliveryStatusData"];
            funnel_24h: components["schemas"]["NewsFunnelData"];
            health: components["schemas"]["NewsHealthData"];
            ingest: components["schemas"]["NewsIngestStatusData"];
            instruments?: components["schemas"]["NewsInstrumentUniverse"];
            /** Measured At Ms */
            measured_at_ms: number;
            pipeline: components["schemas"]["NewsPipelineStatusData"];
            /** Reasons 24H */
            reasons_24h?: components["schemas"]["NewsReasonCountData"][];
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "degraded" | "warming" | "unavailable";
            /** Watchlist */
            watchlist?: string[];
            /** Workers State */
            workers_state?: string | null;
        };
        /** NewsTimelineStepData */
        NewsTimelineStepData: {
            /** At Ms */
            at_ms: number;
            /** Facts */
            facts?: {
                [key: string]: unknown;
            };
            /**
             * Stage
             * @enum {string}
             */
            stage: "received" | "gate" | "triage" | "decide" | "delivery";
            /** Summary Zh */
            summary_zh: string;
            /** Title Zh */
            title_zh: string;
        };
        /** NewsTriageAssetData */
        NewsTriageAssetData: {
            /** Role */
            role: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * NewsTriageSummaryData
         * @description The reader-facing view of one Triage verdict. Every `*_zh` is server-owned copy; the raw enum stays
         *     beside it so the browser can map it to a visual tone without owning a vocabulary table.
         */
        NewsTriageSummaryData: {
            /** Actionable */
            actionable?: boolean | null;
            /** Assets */
            assets?: components["schemas"]["NewsTriageAssetData"][];
            /** Audience */
            audience?: string | null;
            /**
             * Audience Zh
             * @default
             */
            audience_zh: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Decision Zh
             * @default
             */
            decision_zh: string;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Direction */
            direction?: string | null;
            /**
             * Direction Zh
             * @default
             */
            direction_zh: string;
            /** Error Code */
            error_code?: string | null;
            /** Event Type */
            event_type?: string | null;
            /**
             * Event Type Zh
             * @default
             */
            event_type_zh: string;
            /** Final Decision */
            final_decision: string;
            /** Headline Zh */
            headline_zh?: string | null;
            /** Magnitude */
            magnitude?: number | null;
            /**
             * Magnitude Zh
             * @default
             */
            magnitude_zh: string;
            /** Model Decision */
            model_decision?: string | null;
            /**
             * Model Decision Zh
             * @default
             */
            model_decision_zh: string;
            /** Novelty */
            novelty?: string | null;
            /**
             * Novelty Zh
             * @default
             */
            novelty_zh: string;
            /** Override Rule */
            override_rule?: string | null;
            /** Scope */
            scope?: string | null;
            /**
             * Scope Zh
             * @default
             */
            scope_zh: string;
            /** Throttled By */
            throttled_by?: string | null;
            /** Title Zh */
            title_zh?: string | null;
            /** Why Zh */
            why_zh?: string | null;
        };
        /** NewsVerdictData */
        NewsVerdictData: {
            /** Created At Ms */
            created_at_ms: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Error Code */
            error_code?: string | null;
            /** Final Decision */
            final_decision: string;
            /** Model */
            model?: string | null;
            /** Model Decision */
            model_decision?: string | null;
            /** Override Rule */
            override_rule?: string | null;
            /** Policy Version */
            policy_version: string;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Published At Ms */
            published_at_ms?: number | null;
            /** Rule Baseline Decision */
            rule_baseline_decision: string;
            /** Stage */
            stage: string;
            /** Throttled By */
            throttled_by?: string | null;
            /** Trace */
            trace?: {
                [key: string]: unknown;
            };
            /** Verdict */
            verdict?: {
                [key: string]: unknown;
            };
        };
        /** ReadinessData */
        ReadinessData: {
            /** Composition */
            composition: {
                [key: string]: unknown;
            };
            /** Db */
            db: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
            /** Reasons */
            reasons: string[];
            /**
             * Store
             * @constant
             */
            store: "postgresql";
        };
        /** StatusData */
        StatusData: {
            /** Measured At Ms */
            measured_at_ms: number;
            runtime: components["schemas"]["StatusRuntimeData"];
        };
        /** StatusDatabaseData */
        StatusDatabaseData: {
            /** Current Revision */
            current_revision: string | null;
            /** Error Code */
            error_code: ("database_unavailable" | "schema_mismatch") | null;
            /** Expected Revision */
            expected_revision: string;
            /** Ok */
            ok: boolean;
            /** Schema Ok */
            schema_ok: boolean;
        };
        /** StatusRuntimeData */
        StatusRuntimeData: {
            db: components["schemas"]["StatusDatabaseData"];
            /** Ok */
            ok: boolean;
            /** Reasons */
            reasons: ("database_unavailable" | "database_schema_mismatch" | "runtime_status_query_failed" | "runtime_missing" | "runtime_heartbeat_stale" | "runtime_starting" | "runtime_stopping" | "runtime_stopped" | "runtime_failed")[];
            workers_runtime: components["schemas"]["WorkersRuntimeData"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkersRuntimeData */
        WorkersRuntimeData: {
            /** Fatal Code */
            fatal_code: ("startup_failed" | "child_failed" | "control_failed" | "singleton_lost" | "runtime_invariant_failed" | "resource_operation_overrun" | "graceful_deadline_exceeded" | "cleanup_failed") | null;
            /** Heartbeat At Ms */
            heartbeat_at_ms: number | null;
            /**
             * Heartbeat Stale After Ms
             * @constant
             */
            heartbeat_stale_after_ms: 15000;
            /** Runtime Id */
            runtime_id: string | null;
            /** Runtime Version */
            runtime_version: string | null;
            /** Started At Ms */
            started_at_ms: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "running" | "stopping" | "stopped" | "failed" | "stale" | "unavailable";
            /** Unavailable Reason */
            unavailable_reason: ("runtime_status_query_failed" | "runtime_missing" | "runtime_heartbeat_stale" | "runtime_starting" | "runtime_stopping" | "runtime_stopped" | "runtime_failed") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_api_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_BootstrapData_"];
                };
            };
        };
    };
    get_news_event_api_news_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NewsEventDetailData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_feed_api_news_feed_get: {
        parameters: {
            query?: {
                family?: string;
                admission?: string;
                priority?: string;
                decision?: string;
                symbol?: string;
                q?: string;
                sort?: string;
                limit?: number;
                cursor?: string;
                outcome?: string;
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NewsFeedData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_status_api_news_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NewsStatusData_"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StatusData_"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessData"];
                };
            };
        };
    };
}
