/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Alerts */
        get: operations["account_alerts_api_account_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events By Ids */
        get: operations["events_by_ids_api_events_by_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live-market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Market */
        get: operations["live_market_api_live_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/credit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Credit */
        get: operations["macro_credit_api_macro_credit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/cross-asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Cross Asset */
        get: operations["macro_cross_asset_api_macro_cross_asset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/economy-inflation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Economy Inflation */
        get: operations["macro_economy_inflation_api_macro_economy_inflation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/liquidity-funding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Liquidity Funding */
        get: operations["macro_liquidity_funding_api_macro_liquidity_funding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Overview */
        get: operations["macro_overview_api_macro_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/rates-fed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Rates Fed */
        get: operations["macro_rates_fed_api_macro_rates_fed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Research */
        get: operations["macro_research_api_macro_research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/volatility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Volatility */
        get: operations["macro_volatility_api_macro_volatility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News World Brief */
        get: operations["get_news_world_brief_api_news_brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Feed */
        get: operations["get_news_feed_api_news_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Sources */
        get: operations["get_news_sources_api_news_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Status */
        get: operations["get_news_status_api_news_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Story */
        get: operations["get_news_story_api_news_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification Deliveries */
        get: operations["notification_deliveries_api_notification_deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/author/{author_handle}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Author Notifications Read */
        post: operations["mark_author_notifications_read_api_notifications_author__author_handle__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Notifications Read */
        post: operations["mark_all_notifications_read_api_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Inspect */
        get: operations["search_inspect_api_search_inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stocks Radar */
        get: operations["stocks_radar_api_stocks_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Posts */
        get: operations["target_posts_api_target_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-social-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Social Timeline */
        get: operations["target_social_timeline_api_target_social_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token-case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token Case */
        get: operations["token_case_api_token_case_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token Radar */
        get: operations["token_radar_api_token_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Overview */
        get: operations["watchlist_handle_overview_api_watchlist_handle__handle__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handle/{handle}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handle Timeline */
        get: operations["watchlist_handle_timeline_api_watchlist_handle__handle__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/handles/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Handles Overview */
        get: operations["watchlist_handles_overview_api_watchlist_handles_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountAlertsData */
        AccountAlertsData: {
            /** Alert Type */
            alert_type: string | null;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Window */
            window: string;
        };
        /** ApiEnvelope[AccountAlertsData] */
        ApiEnvelope_AccountAlertsData_: {
            data?: components["schemas"]["AccountAlertsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[BootstrapData] */
        ApiEnvelope_BootstrapData_: {
            data?: components["schemas"]["BootstrapData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[LiveMarketData] */
        ApiEnvelope_LiveMarketData_: {
            data?: components["schemas"]["LiveMarketData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[MacroModuleReadData] */
        ApiEnvelope_MacroModuleReadData_: {
            data?: components["schemas"]["MacroModuleReadData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[MacroOverviewReadData] */
        ApiEnvelope_MacroOverviewReadData_: {
            data?: components["schemas"]["MacroOverviewReadData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[MacroResearchReadData] */
        ApiEnvelope_MacroResearchReadData_: {
            data?: components["schemas"]["MacroResearchReadData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NotificationDeliveriesData] */
        ApiEnvelope_NotificationDeliveriesData_: {
            data?: components["schemas"]["NotificationDeliveriesData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NotificationReadAllData] */
        ApiEnvelope_NotificationReadAllData_: {
            data?: components["schemas"]["NotificationReadAllData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NotificationReadData] */
        ApiEnvelope_NotificationReadData_: {
            data?: components["schemas"]["NotificationReadData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[NotificationsData] */
        ApiEnvelope_NotificationsData_: {
            data?: components["schemas"]["NotificationsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[RecentData] */
        ApiEnvelope_RecentData_: {
            data?: components["schemas"]["RecentData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[SearchData] */
        ApiEnvelope_SearchData_: {
            data?: components["schemas"]["SearchData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[SearchInspectData] */
        ApiEnvelope_SearchInspectData_: {
            data?: components["schemas"]["SearchInspectData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[SourceEventsByIdsData] */
        ApiEnvelope_SourceEventsByIdsData_: {
            data?: components["schemas"]["SourceEventsByIdsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[StatusData] */
        ApiEnvelope_StatusData_: {
            data?: components["schemas"]["StatusData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[StocksRadarData] */
        ApiEnvelope_StocksRadarData_: {
            data?: components["schemas"]["StocksRadarData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[TargetPostsData] */
        ApiEnvelope_TargetPostsData_: {
            data?: components["schemas"]["TargetPostsData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[TargetSocialTimelineData] */
        ApiEnvelope_TargetSocialTimelineData_: {
            data?: components["schemas"]["TargetSocialTimelineData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[TokenCaseData] */
        ApiEnvelope_TokenCaseData_: {
            data?: components["schemas"]["TokenCaseData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[TokenRadarData] */
        ApiEnvelope_TokenRadarData_: {
            data?: components["schemas"]["TokenRadarData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[WatchlistHandleOverviewData] */
        ApiEnvelope_WatchlistHandleOverviewData_: {
            data?: components["schemas"]["WatchlistHandleOverviewData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[WatchlistHandleTimelineData] */
        ApiEnvelope_WatchlistHandleTimelineData_: {
            data?: components["schemas"]["WatchlistHandleTimelineData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[WatchlistHandlesOverviewData] */
        ApiEnvelope_WatchlistHandlesOverviewData_: {
            data?: components["schemas"]["WatchlistHandlesOverviewData"] | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ApiEnvelope[dict[str, Any]] */
        ApiEnvelope_dict_str__Any__: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Field */
            field?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** BootstrapData */
        BootstrapData: {
            /** Handles */
            handles: string[];
            /** Replay Limit */
            replay_limit: number;
            /** Ws Token */
            ws_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveMarketData */
        LiveMarketData: {
            /** Age Ms */
            age_ms: number | null;
            /** Holders */
            holders: number | null;
            /** Liquidity Usd */
            liquidity_usd: number | null;
            /** Market Cap Usd */
            market_cap_usd: number | null;
            /** Observed At Ms */
            observed_at_ms: number | null;
            /** Open Interest Usd */
            open_interest_usd: number | null;
            /**
             * Price Basis
             * @enum {string}
             */
            price_basis: "usd" | "quote_as_usd" | "unavailable";
            /** Price Quote */
            price_quote: number | null;
            /** Price Usd */
            price_usd: number | null;
            /** Provider */
            provider: string | null;
            /** Quote Symbol */
            quote_symbol: string | null;
            /** Received At Ms */
            received_at_ms: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "stale" | "missing";
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
            /** Volume 24H Usd */
            volume_24h_usd: number | null;
        };
        /** MacroModuleReadData */
        MacroModuleReadData: {
            /** Charts */
            charts: {
                [key: string]: unknown;
            }[];
            /** Contradictions */
            contradictions: string[];
            /** Current State */
            current_state: {
                [key: string]: unknown;
            };
            /** Dataset States */
            dataset_states: {
                [key: string]: unknown;
            }[];
            /** Falsifiers */
            falsifiers: string[];
            /** Features */
            features: {
                [key: string]: unknown;
            }[];
            /** Gaps */
            gaps: {
                [key: string]: unknown;
            }[];
            /** Judgment Cutoff Ms */
            judgment_cutoff_ms: number | null;
            /** Label */
            label: string;
            /** Latest Fact At Ms */
            latest_fact_at_ms: number;
            /**
             * Module Id
             * @enum {string}
             */
            module_id: "rates_fed" | "economy_inflation" | "liquidity_funding" | "credit" | "volatility" | "cross_asset";
            /** Next Checkpoints */
            next_checkpoints: {
                [key: string]: unknown;
            }[];
            /** Raw Evidence */
            raw_evidence: {
                [key: string]: unknown;
            }[];
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "ready" | "degraded" | "blocked";
            /**
             * Schema Version
             * @constant
             */
            schema_version: "macro_module_v1";
            /** Top Changes */
            top_changes: {
                [key: string]: unknown;
            }[];
        };
        /** MacroModuleSummaryData */
        MacroModuleSummaryData: {
            /** Current State */
            current_state: {
                [key: string]: unknown;
            } | null;
            /** Gap Count */
            gap_count: number;
            /** Href */
            href: string;
            /** Label */
            label: string;
            /** Latest Fact At Ms */
            latest_fact_at_ms: number;
            /** Module Id */
            module_id: string;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "ready" | "degraded" | "blocked" | "missing";
            /** Top Changes */
            top_changes: {
                [key: string]: unknown;
            }[];
        };
        /** MacroOverviewReadData */
        MacroOverviewReadData: {
            /** Changes Since Judgment */
            changes_since_judgment: {
                [key: string]: unknown;
            }[];
            /** Daily Judgment */
            daily_judgment: {
                [key: string]: unknown;
            } | null;
            /** Judgment Cutoff Ms */
            judgment_cutoff_ms: number | null;
            /** Latest Fact At Ms */
            latest_fact_at_ms: number;
            /** Modules */
            modules: components["schemas"]["MacroModuleSummaryData"][];
            /**
             * Overall Readiness
             * @enum {string}
             */
            overall_readiness: "ready" | "degraded" | "blocked";
            /** Read At Ms */
            read_at_ms: number;
            /** Research */
            research: {
                [key: string]: unknown;
            };
            /**
             * Schema Version
             * @constant
             */
            schema_version: "macro_overview_v1";
        };
        /** MacroResearchCitationData */
        MacroResearchCitationData: {
            /** Available At Ms */
            available_at_ms?: number | null;
            /** Citation Id */
            citation_id: string;
            /** Lineage */
            lineage?: {
                [key: string]: unknown;
            };
            /** Observed At */
            observed_at?: string | null;
            /** Published At Ms */
            published_at_ms?: number | null;
            /** Source Label */
            source_label: string;
            /** Source Ref */
            source_ref: string;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** MacroResearchEvidenceGapData */
        MacroResearchEvidenceGapData: {
            /** Citation Ids */
            citation_ids?: string[];
            /** Details */
            details?: string | null;
            /** Gap Id */
            gap_id: string;
            /** Summary */
            summary: string;
        };
        /** MacroResearchPublicationData */
        MacroResearchPublicationData: {
            /** Audit */
            audit: {
                [key: string]: unknown;
            };
            /** Citations */
            citations: components["schemas"]["MacroResearchCitationData"][];
            /** Evidence Gaps */
            evidence_gaps: components["schemas"]["MacroResearchEvidenceGapData"][];
            /** Evidence Pack Id */
            evidence_pack_id: string;
            /** Executive Summary */
            executive_summary: string;
            /** Market Cutoff Ms */
            market_cutoff_ms: number;
            /** Published At Ms */
            published_at_ms?: number | null;
            /**
             * Reviewer Disposition
             * @enum {string}
             */
            reviewer_disposition: "pass" | "revise" | "block";
            /** Reviewer Notes */
            reviewer_notes: string[];
            /** Schema Version */
            schema_version: string;
            /** Sections */
            sections: components["schemas"]["MacroResearchSectionData"][];
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            /** Title */
            title: string;
        };
        /** MacroResearchReadData */
        MacroResearchReadData: {
            /**
             * Current Session Date
             * Format: date
             */
            current_session_date: string;
            publication: components["schemas"]["MacroResearchPublicationData"] | null;
            /**
             * Requested Session Date
             * Format: date
             */
            requested_session_date: string;
            run: components["schemas"]["MacroResearchRunData"] | null;
            /**
             * State
             * @enum {string}
             */
            state: "current" | "historical" | "generating" | "failed" | "missing";
        };
        /** MacroResearchRunData */
        MacroResearchRunData: {
            /** Attempt Count */
            attempt_count: number;
            /** Evidence Pack Id */
            evidence_pack_id: string;
            /** Last Error */
            last_error: string | null;
            /** Max Attempts */
            max_attempts: number;
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            /** Status */
            status: string;
            /** Updated At Ms */
            updated_at_ms: number;
        };
        /** MacroResearchSectionData */
        MacroResearchSectionData: {
            /** Body Markdown */
            body_markdown: string;
            /** Citation Ids */
            citation_ids: string[];
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
        };
        /** NewsHealthData */
        NewsHealthData: {
            layers: components["schemas"]["NewsHealthLayersData"];
            /** Measured At Ms */
            measured_at_ms: number;
            /** Reasons */
            reasons: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "warming" | "ready" | "degraded";
        };
        /** NewsHealthLayerData */
        NewsHealthLayerData: {
            /**
             * Status
             * @enum {string}
             */
            status: "warming" | "ready" | "degraded";
        } & {
            [key: string]: unknown;
        };
        /** NewsHealthLayersData */
        NewsHealthLayersData: {
            brief: components["schemas"]["NewsHealthLayerData"];
            ingest: components["schemas"]["NewsHealthLayerData"];
            story: components["schemas"]["NewsHealthLayerData"];
        };
        /** NotificationDeliveriesData */
        NotificationDeliveriesData: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** NotificationItemData */
        NotificationItemData: {
            /** Address */
            address: string | null;
            /** Author Handle */
            author_handle: string | null;
            /** Body */
            body: string;
            /** Chain */
            chain: string | null;
            /** Channels */
            channels: string[];
            /** Created At Ms */
            created_at_ms: number;
            /** Dedup Key */
            dedup_key: string;
            /** Entity Key */
            entity_key: string | null;
            /** Entity Type */
            entity_type: string | null;
            /** Event Id */
            event_id: string | null;
            /** First Seen At Ms */
            first_seen_at_ms: number;
            /** Last Seen At Ms */
            last_seen_at_ms: number;
            /** Notification Id */
            notification_id: string;
            /** Occurrence Count */
            occurrence_count: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Read At Ms */
            read_at_ms: number | null;
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Source Id */
            source_id: string;
            /** Source Table */
            source_table: string;
            /** Symbol */
            symbol: string | null;
            /** Title */
            title: string;
            /** Updated At Ms */
            updated_at_ms: number;
        };
        /** NotificationReadAllData */
        NotificationReadAllData: {
            /** Updated Count */
            updated_count: number;
        };
        /** NotificationReadData */
        NotificationReadData: {
            /** Notification Id */
            notification_id: string;
            /** Updated */
            updated: boolean;
        };
        /** NotificationSummary */
        NotificationSummary: {
            /** Account Unread Counts */
            account_unread_counts: {
                [key: string]: number;
            };
            /** Critical Unread Count */
            critical_unread_count: number;
            /** High Unread Count */
            high_unread_count: number;
            /** Highest Unread Severity */
            highest_unread_severity: string | null;
            /** Subscriber Key */
            subscriber_key: string;
            /** Unread Count */
            unread_count: number;
        };
        /** NotificationsData */
        NotificationsData: {
            /** Items */
            items: components["schemas"]["NotificationItemData"][];
            summary: components["schemas"]["NotificationSummary"];
        };
        /** ReadinessData */
        ReadinessData: {
            /** Composition */
            composition: {
                [key: string]: unknown;
            };
            /** Db */
            db: {
                [key: string]: unknown;
            };
            /** Handles */
            handles: string[];
            /** Ok */
            ok: boolean;
            /** Reasons */
            reasons: string[];
            /**
             * Store
             * @constant
             */
            store: "postgresql";
        };
        /** RecentData */
        RecentData: {
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Scope */
            scope: string;
        };
        /** SearchData */
        SearchData: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            page: components["schemas"]["SearchPageData"];
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Target Candidates */
            target_candidates: {
                [key: string]: unknown;
            }[];
        };
        /** SearchInspectAmbiguousData */
        SearchInspectAmbiguousData: {
            /** Candidates */
            candidates: {
                [key: string]: unknown;
            }[];
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            summary: components["schemas"]["SearchInspectTopicSummaryData"];
        };
        /** SearchInspectData */
        SearchInspectData: {
            ambiguous_result: components["schemas"]["SearchInspectAmbiguousData"] | null;
            query: components["schemas"]["SearchInspectQueryData"];
            resolver: components["schemas"]["SearchInspectResolverData"];
            token_result: components["schemas"]["TokenCaseData"] | null;
            topic_result: components["schemas"]["SearchInspectTopicData"] | null;
        };
        /** SearchInspectQueryData */
        SearchInspectQueryData: {
            /** Normalized Q */
            normalized_q: string;
            /** Q */
            q: string;
            /**
             * Result Kind
             * @enum {string}
             */
            result_kind: "token_result" | "topic_result" | "ambiguous_result" | "empty_result";
            /** Scope */
            scope: string;
            /** Window */
            window: string;
        };
        /** SearchInspectResolverData */
        SearchInspectResolverData: {
            /** Reasons */
            reasons: string[];
            /** Selected Target */
            selected_target: {
                [key: string]: unknown;
            } | null;
            /** Target Candidates */
            target_candidates: {
                [key: string]: unknown;
            }[];
        };
        /** SearchInspectTopicData */
        SearchInspectTopicData: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            summary: components["schemas"]["SearchInspectTopicSummaryData"];
        };
        /** SearchInspectTopicSummaryData */
        SearchInspectTopicSummaryData: {
            /** Authors */
            authors: number;
            /** Posts */
            posts: number;
        };
        /** SearchPageData */
        SearchPageData: {
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor: string | null;
            /** Returned Count */
            returned_count: number;
        };
        /** SourceEventDetail */
        SourceEventDetail: {
            /** Action */
            action: string;
            /** Author Followers */
            author_followers: number | null;
            /** Author Handle */
            author_handle: string | null;
            /** Author Name */
            author_name: string | null;
            /** Author Watched */
            author_watched: boolean;
            /** Canonical Url */
            canonical_url: string | null;
            /** Channel */
            channel: string;
            /** Event Id */
            event_id: string;
            /** Source Provider */
            source_provider: string;
            /** Text Clean */
            text_clean: string | null;
            /** Timestamp Ms */
            timestamp_ms: number;
        };
        /** SourceEventsByIdsData */
        SourceEventsByIdsData: {
            /** Events */
            events: components["schemas"]["SourceEventDetail"][];
            /** Not Found */
            not_found: string[];
        };
        /** StatusData */
        StatusData: {
            /** Db */
            db: {
                [key: string]: unknown;
            };
            /** Handles */
            handles: string[];
            news: components["schemas"]["NewsHealthData"];
            /** Ok */
            ok: boolean;
            /** Provider States */
            provider_states: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Reasons */
            reasons: string[];
            /** Snapshot Gate */
            snapshot_gate: {
                [key: string]: unknown;
            };
            /**
             * Store
             * @constant
             */
            store: "postgresql";
            /** Workers */
            workers: {
                [key: string]: components["schemas"]["WorkerStatusData"];
            };
        };
        /** StocksRadarAttentionData */
        StocksRadarAttentionData: {
            /** Latest Seen Ms */
            latest_seen_ms: number | null;
            /** Mentions */
            mentions: number;
            /** Unique Authors */
            unique_authors: number;
            /** Watched Mentions */
            watched_mentions: number;
        };
        /** StocksRadarData */
        StocksRadarData: {
            health: components["schemas"]["StocksRadarHealthData"];
            query: components["schemas"]["StocksRadarQueryData"];
            /** Rows */
            rows: components["schemas"]["StocksRadarRowData"][];
            /** Scope */
            scope: string;
            /** Window */
            window: string;
        };
        /** StocksRadarHealthData */
        StocksRadarHealthData: {
            /** Quote Ready Count */
            quote_ready_count: number;
            /** Quote Unavailable Count */
            quote_unavailable_count: number;
            /** Returned Count */
            returned_count: number;
        };
        /** StocksRadarLatestEventData */
        StocksRadarLatestEventData: {
            /** Author Handle */
            author_handle: string | null;
            /** Event Id */
            event_id: string | null;
            /** Received At Ms */
            received_at_ms: number | null;
            /** Text */
            text: string | null;
        };
        /** StocksRadarQueryData */
        StocksRadarQueryData: {
            /** Limit */
            limit: number;
            /** Scope */
            scope: string;
            /** Window */
            window: string;
            /** Window End Ms */
            window_end_ms: number;
            /** Window Start Ms */
            window_start_ms: number;
        };
        /** StocksRadarQuoteData */
        StocksRadarQuoteData: {
            /** Asof */
            asof: string | null;
            /** Change Pct */
            change_pct: number | null;
            /** Error */
            error: string | null;
            /** Freshness Class */
            freshness_class: string | null;
            /** Latency Class */
            latency_class: string | null;
            /** Price */
            price: number | null;
            /** Provider */
            provider: string | null;
            /** Provider Symbol */
            provider_symbol: string | null;
            /** Reference Close Price */
            reference_close_price: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
        };
        /** StocksRadarRowData */
        StocksRadarRowData: {
            attention: components["schemas"]["StocksRadarAttentionData"];
            latest_event: components["schemas"]["StocksRadarLatestEventData"];
            quote: components["schemas"]["StocksRadarQuoteData"];
            /** Row Health */
            row_health: string[];
            /** Source Event Ids */
            source_event_ids: string[];
            target: components["schemas"]["StocksRadarTargetData"];
        };
        /** StocksRadarTargetData */
        StocksRadarTargetData: {
            /** Exchange */
            exchange: string | null;
            /** Instrument Type */
            instrument_type: string | null;
            /**
             * Market
             * @constant
             */
            market: "us_equity";
            /** Name */
            name: string | null;
            /** Symbol */
            symbol: string | null;
            /** Target Id */
            target_id: string | null;
            /**
             * Target Type
             * @constant
             */
            target_type: "MarketInstrument";
        };
        /** TargetPostsData */
        TargetPostsData: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor: string | null;
            query: components["schemas"]["TargetPostsQueryData"];
            /** Returned Count */
            returned_count: number;
            score_window: components["schemas"]["TargetPostsScoreWindowData"];
            /** Total Count */
            total_count: number;
        };
        /** TargetPostsQueryData */
        TargetPostsQueryData: {
            /** Range */
            range: string;
            /** Scope */
            scope: string;
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
            /** Window */
            window: string;
        };
        /** TargetPostsScoreWindowData */
        TargetPostsScoreWindowData: {
            /** Window */
            window: string;
        };
        /** TargetSocialTimelineData */
        TargetSocialTimelineData: {
            /** Authors */
            authors: {
                [key: string]: unknown;
            }[];
            /** Buckets */
            buckets: {
                [key: string]: unknown;
            }[];
            /** Cascade */
            cascade: {
                [key: string]: unknown;
            };
            /** Has More */
            has_more: boolean;
            /** Market Candles */
            market_candles: {
                [key: string]: unknown;
            } | null;
            /** Next Cursor */
            next_cursor: string | null;
            /** Posts */
            posts: {
                [key: string]: unknown;
            }[];
            query: components["schemas"]["TargetSocialTimelineQueryData"];
            /** Returned Count */
            returned_count: number;
            /** Stages */
            stages: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** TargetSocialTimelineQueryData */
        TargetSocialTimelineQueryData: {
            /** Bucket */
            bucket: string;
            /** Scope */
            scope: string;
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
            /** Window */
            window: string;
        };
        /** TokenCaseData */
        TokenCaseData: {
            current_radar: components["schemas"]["TokenRadarFactRowData"] | null;
            /** Market Live */
            market_live: {
                [key: string]: unknown;
            };
            /** Posts */
            posts: {
                [key: string]: unknown;
            };
            /** Profile */
            profile: {
                [key: string]: unknown;
            } | null;
            /** Target */
            target: {
                [key: string]: unknown;
            };
            /** Timeline */
            timeline: {
                [key: string]: unknown;
            };
        };
        /** TokenFactorCompositeData */
        TokenFactorCompositeData: {
            family_scores: components["schemas"]["TokenFactorFamilyValuesData"];
            /** Rank Score */
            rank_score: number;
            /** Raw Alpha Score */
            raw_alpha_score: number;
            /**
             * Recommended Decision
             * @enum {string}
             */
            recommended_decision: "discard" | "watch" | "high_alert";
        };
        /** TokenFactorFamiliesData */
        TokenFactorFamiliesData: {
            social_heat: components["schemas"]["TokenFactorFamilyData"];
            social_propagation: components["schemas"]["TokenFactorFamilyData"];
            timing_risk: components["schemas"]["TokenFactorFamilyData"];
        };
        /** TokenFactorFamilyData */
        TokenFactorFamilyData: {
            /** Data Health */
            data_health: string;
            /** Factors */
            factors: {
                [key: string]: unknown;
            };
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
            /** Raw Score */
            raw_score: number;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
        };
        /** TokenFactorFamilyValuesData */
        TokenFactorFamilyValuesData: {
            /** Social Heat */
            social_heat: number;
            /** Social Propagation */
            social_propagation: number;
            /** Timing Risk */
            timing_risk: number;
        };
        /** TokenFactorGatesData */
        TokenFactorGatesData: {
            /** Blocked Reasons */
            blocked_reasons: string[];
            /** Eligible For High Alert */
            eligible_for_high_alert: boolean;
            /**
             * Max Decision
             * @enum {string}
             */
            max_decision: "discard" | "watch" | "high_alert";
            /** Risk Reasons */
            risk_reasons: string[];
        };
        /** TokenFactorMarketData */
        TokenFactorMarketData: {
            /** Capture Method */
            capture_method?: string | null;
            /** Capture Reason */
            capture_reason?: string | null;
            /** Decision Latest */
            decision_latest: {
                [key: string]: unknown;
            } | null;
            /** Event Anchor */
            event_anchor: {
                [key: string]: unknown;
            } | null;
            readiness: components["schemas"]["TokenFactorMarketReadinessData"];
            /** Tick Lag Ms */
            tick_lag_ms?: number | null;
        };
        /** TokenFactorMarketReadinessData */
        TokenFactorMarketReadinessData: {
            /** Anchor Status */
            anchor_status: string;
            /** Dex Floor Status */
            dex_floor_status: string;
            /** Latest Status */
            latest_status: string;
            /** Missing Fields */
            missing_fields: string[];
            /** Stale Fields */
            stale_fields: string[];
        };
        /** TokenFactorNormalizationData */
        TokenFactorNormalizationData: {
            /** Alpha Rank */
            alpha_rank: number | null;
            /** Cohort */
            cohort: {
                [key: string]: unknown;
            };
            /** Cohort Status */
            cohort_status: string;
            factor_ranks: components["schemas"]["TokenFactorRankValuesData"];
            /** Status */
            status: string;
        };
        /** TokenFactorProvenanceData */
        TokenFactorProvenanceData: {
            /** Computed At Ms */
            computed_at_ms: number;
            /** Source Event Ids */
            source_event_ids: string[];
        };
        /** TokenFactorRankValuesData */
        TokenFactorRankValuesData: {
            /** Social Heat */
            social_heat: number | null;
            /** Social Propagation */
            social_propagation: number | null;
            /** Timing Risk */
            timing_risk: number | null;
        };
        /** TokenFactorSnapshotData */
        TokenFactorSnapshotData: {
            composite: components["schemas"]["TokenFactorCompositeData"];
            /** Data Health */
            data_health: {
                [key: string]: unknown;
            };
            families: components["schemas"]["TokenFactorFamiliesData"];
            gates: components["schemas"]["TokenFactorGatesData"];
            market: components["schemas"]["TokenFactorMarketData"];
            normalization: components["schemas"]["TokenFactorNormalizationData"];
            provenance: components["schemas"]["TokenFactorProvenanceData"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "token_factor_snapshot_v4_transparent_factors";
            subject: components["schemas"]["TokenFactorSubjectData"];
        };
        /** TokenFactorSubjectData */
        TokenFactorSubjectData: {
            /** Address */
            address: string | null;
            /** Chain */
            chain: string | null;
            /** Pricefeed Id */
            pricefeed_id: string | null;
            /** Symbol */
            symbol: string | null;
            /** Target Id */
            target_id: string | null;
            /** Target Market Type */
            target_market_type: string | null;
            /** Target Type */
            target_type: string | null;
        };
        /** TokenRadarAnchorCoverageData */
        TokenRadarAnchorCoverageData: {
            /** Missing */
            missing: number;
            /** Ready */
            ready: number;
            /** Status */
            status: string;
            /** Total */
            total: number;
        };
        /** TokenRadarData */
        TokenRadarData: {
            /** Attention */
            attention: components["schemas"]["TokenRadarRowData"][];
            projection: components["schemas"]["TokenRadarProjectionData"];
            /** Scope */
            scope: string;
            /** Targets */
            targets: components["schemas"]["TokenRadarRowData"][];
            /** Venue */
            venue: string;
            /** Window */
            window: string;
        };
        /** TokenRadarFactRowData */
        TokenRadarFactRowData: {
            factor_snapshot: components["schemas"]["TokenFactorSnapshotData"];
            intent: components["schemas"]["TokenRadarIntentData"];
            quality: components["schemas"]["TokenRadarQualityData"];
            radar: components["schemas"]["TokenRadarMetaData"];
            resolution: components["schemas"]["TokenRadarResolutionData"];
        };
        /** TokenRadarIntentData */
        TokenRadarIntentData: {
            /** Display Name */
            display_name?: string | null;
            /** Display Symbol */
            display_symbol?: string | null;
            /** Event Id */
            event_id: string;
            /** Evidence */
            evidence: unknown[];
            /** Intent Id */
            intent_id: string;
        };
        /** TokenRadarMetaData */
        TokenRadarMetaData: {
            /** Computed At Ms */
            computed_at_ms?: number | null;
            /** Lane */
            lane?: string | null;
            /** Listed At Ms */
            listed_at_ms?: number | null;
            /** Rank */
            rank?: number | null;
            /** Source Max Received At Ms */
            source_max_received_at_ms?: number | null;
        };
        /** TokenRadarProjectionData */
        TokenRadarProjectionData: {
            anchor_coverage: components["schemas"]["TokenRadarAnchorCoverageData"];
            /** Computed At Ms */
            computed_at_ms: number | null;
            /** Degraded Reasons */
            degraded_reasons: string[];
            /** Error */
            error: string | null;
            /** Latest Attempt Status */
            latest_attempt_status: string;
            /**
             * Quality Status
             * @enum {string}
             */
            quality_status: "ready" | "degraded" | "insufficient" | "failed";
            /** Reason */
            reason: string | null;
            /** Row Count */
            row_count: number;
            /**
             * Source
             * @constant
             */
            source: "token_radar_current_rows";
            /** Source Frontier Ms */
            source_frontier_ms: number | null;
            /** Source Max Received At Ms */
            source_max_received_at_ms: number;
            /** Source Rows */
            source_rows: number;
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "stale" | "pending" | "failed";
            unresolved: components["schemas"]["TokenRadarUnresolvedData"];
            /** Venue */
            venue: string;
            /** Version */
            version: string;
        };
        /** TokenRadarQualityData */
        TokenRadarQualityData: {
            /** Degraded Reasons */
            degraded_reasons: string[];
            /** Status */
            status: string;
        };
        /** TokenRadarResolutionData */
        TokenRadarResolutionData: {
            /** Candidate Ids */
            candidate_ids: string[];
            /** Discovery */
            discovery: {
                [key: string]: unknown;
            }[];
            /** Lookup Keys */
            lookup_keys: string[];
            /** Pricefeed Id */
            pricefeed_id: string | null;
            /** Reason Codes */
            reason_codes: string[];
            /** Status */
            status: string;
            /** Target Id */
            target_id: string | null;
            /** Target Type */
            target_type: string | null;
        };
        /** TokenRadarRowData */
        TokenRadarRowData: {
            factor_snapshot: components["schemas"]["TokenFactorSnapshotData"];
            intent: components["schemas"]["TokenRadarIntentData"];
            /** Profile */
            profile?: {
                [key: string]: unknown;
            } | null;
            quality: components["schemas"]["TokenRadarQualityData"];
            radar: components["schemas"]["TokenRadarMetaData"];
            resolution: components["schemas"]["TokenRadarResolutionData"];
        };
        /** TokenRadarUnresolvedData */
        TokenRadarUnresolvedData: {
            /** Ambiguous Count */
            ambiguous_count: number;
            /** Identity Missing Count */
            identity_missing_count: number;
            /** Nil Count */
            nil_count: number;
            /** Sample Symbols */
            sample_symbols: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistHandleOverviewData */
        WatchlistHandleOverviewData: {
            /** Candidate Mention Clusters */
            candidate_mention_clusters: components["schemas"]["WatchlistOverviewCluster"][];
            /** Clusters Truncated */
            clusters_truncated: boolean;
            /** Hashtag Clusters */
            hashtag_clusters: components["schemas"]["WatchlistOverviewCluster"][];
            metrics: components["schemas"]["WatchlistOverviewMetrics"];
            query: components["schemas"]["WatchlistOverviewQuery"];
            /** Resolved Token Clusters */
            resolved_token_clusters: components["schemas"]["WatchlistOverviewCluster"][];
            /** Risk Notes */
            risk_notes: string[];
        };
        /** WatchlistHandleRowOverview */
        WatchlistHandleRowOverview: {
            /** Handle */
            handle: string;
            /** Last Source Event At Ms */
            last_source_event_at_ms: number | null;
            /** Recent Source Event Count */
            recent_source_event_count: number;
        };
        /** WatchlistHandleTimelineData */
        WatchlistHandleTimelineData: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["WatchlistTimelineItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            query: components["schemas"]["WatchlistTimelineQuery"];
        };
        /** WatchlistHandlesOverviewData */
        WatchlistHandlesOverviewData: {
            /** Items */
            items: components["schemas"]["WatchlistHandleRowOverview"][];
            /** Window */
            window: string;
        };
        /** WatchlistOverviewCluster */
        WatchlistOverviewCluster: {
            /** Count */
            count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resolved_token" | "candidate_mention" | "hashtag";
            /** Label */
            label: string;
            /** Query */
            query: string;
            /** Source */
            source: string;
            /** Symbol */
            symbol: string | null;
            /** Target Id */
            target_id: string | null;
            /** Target Type */
            target_type: string | null;
        };
        /** WatchlistOverviewMetrics */
        WatchlistOverviewMetrics: {
            /** Candidate Mention Count */
            candidate_mention_count: number;
            /** Hashtag Count */
            hashtag_count: number;
            /** Last Source Event At Ms */
            last_source_event_at_ms: number | null;
            /** Resolved Token Count */
            resolved_token_count: number;
            /** Source Event Count */
            source_event_count: number;
        };
        /** WatchlistOverviewQuery */
        WatchlistOverviewQuery: {
            /** Handle */
            handle: string;
            /** Window */
            window: string;
        };
        /** WatchlistTimelineItem */
        WatchlistTimelineItem: {
            /** Action */
            action: string;
            /** Author Handle */
            author_handle: string | null;
            /** Canonical Url */
            canonical_url: string | null;
            /** Cashtags */
            cashtags: string[];
            /** Event */
            event: {
                [key: string]: unknown;
            };
            /** Event Id */
            event_id: string;
            /** Hashtags */
            hashtags: string[];
            /** Mentions */
            mentions: string[];
            /** Received At Ms */
            received_at_ms: number;
            /** Text Clean */
            text_clean: string | null;
            /** Token Resolutions */
            token_resolutions: {
                [key: string]: unknown;
            }[];
        };
        /** WatchlistTimelineQuery */
        WatchlistTimelineQuery: {
            /** Handle */
            handle: string;
            /** Limit */
            limit: number;
        };
        /** WorkerStatusData */
        WorkerStatusData: {
            /**
             * Effective Status
             * @enum {string}
             */
            effective_status: "disabled" | "intentionally_not_started" | "unavailable" | "degraded" | "running" | "stopped" | "failed";
            /** Enabled */
            enabled: boolean;
            /** Iteration Duration P99 Ms */
            iteration_duration_p99_ms: number | null;
            /** Last Error */
            last_error: string | null;
            /** Last Finished At Ms */
            last_finished_at_ms: number | null;
            /** Last Result */
            last_result: {
                [key: string]: unknown;
            } | null;
            /** Last Started At Ms */
            last_started_at_ms: number | null;
            /** Running */
            running: boolean;
            /** Unavailable Reason */
            unavailable_reason: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_alerts_api_account_alerts_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                handles?: string;
                alert_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_AccountAlertsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_BootstrapData_"];
                };
            };
        };
    };
    events_by_ids_api_events_by_ids_get: {
        parameters: {
            query?: {
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SourceEventsByIdsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_market_api_live_market_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_LiveMarketData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_credit_api_macro_credit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroModuleReadData_"];
                };
            };
        };
    };
    macro_cross_asset_api_macro_cross_asset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroModuleReadData_"];
                };
            };
        };
    };
    macro_economy_inflation_api_macro_economy_inflation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroModuleReadData_"];
                };
            };
        };
    };
    macro_liquidity_funding_api_macro_liquidity_funding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroModuleReadData_"];
                };
            };
        };
    };
    macro_overview_api_macro_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroOverviewReadData_"];
                };
            };
        };
    };
    macro_rates_fed_api_macro_rates_fed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroModuleReadData_"];
                };
            };
        };
    };
    macro_research_api_macro_research_get: {
        parameters: {
            query?: {
                session_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroResearchReadData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_volatility_api_macro_volatility_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_MacroModuleReadData_"];
                };
            };
        };
    };
    get_news_world_brief_api_news_brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
        };
    };
    get_news_feed_api_news_feed_get: {
        parameters: {
            query?: {
                category?: string;
                level?: string;
                source_id?: string;
                sort?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_sources_api_news_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
        };
    };
    get_news_status_api_news_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
        };
    };
    get_news_story_api_news_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notification_deliveries_api_notification_deliveries_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationDeliveriesData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                unread_only?: boolean;
                rule_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_author_notifications_read_api_notifications_author__author_handle__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadAllData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_notifications_read_api_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadAllData_"];
                };
            };
        };
    };
    mark_notification_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NotificationReadData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_api_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                handles?: string;
                ca?: string;
                chain?: string;
                symbol?: string;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_RecentData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                scope?: string;
                cursor?: string;
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SearchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_inspect_api_search_inspect_get: {
        parameters: {
            query?: {
                q?: string;
                window?: string;
                scope?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SearchInspectData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StatusData_"];
                };
            };
        };
    };
    stocks_radar_api_stocks_radar_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_StocksRadarData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_posts_api_target_posts_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                range?: string;
                limit?: number;
                scope?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TargetPostsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_social_timeline_api_target_social_timeline_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                scope?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TargetSocialTimelineData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_case_api_token_case_get: {
        parameters: {
            query?: {
                target_type?: string;
                target_id?: string;
                window?: string;
                scope?: string;
                posts_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TokenCaseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_radar_api_token_radar_get: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
                scope?: string;
                venue?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TokenRadarData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_overview_api_watchlist_handle__handle__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleOverviewData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handle_timeline_api_watchlist_handle__handle__timeline_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandleTimelineData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_handles_overview_api_watchlist_handles_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WatchlistHandlesOverviewData_"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessData"];
                };
            };
        };
    };
}
