# scripts/regen_db_schema.py
"""Regenerate docs/generated/db-schema.md from Alembic head + pg_catalog introspection.

Requires Postgres reachable via the standard project config.

Import note: the storage module uses psycopg directly (no SQLAlchemy engine).
We follow the same pattern as tracefold/platform/postgres/alembic/env.py:
build a postgresql+psycopg URL via local_docker_host_dsn / with_password_from_file
and pass it to sqlalchemy.create_engine for inspection-only access.
"""

from __future__ import annotations

import os
from pathlib import Path

from sqlalchemy import create_engine, inspect
from sqlalchemy.engine import Connection

from tracefold.platform.config.loader import load_settings
from tracefold.platform.config.models import Settings
from tracefold.platform.postgres.audit import NEWS_TABLES, TRADING_TABLES
from tracefold.platform.postgres.client import local_docker_host_dsn, with_password_from_file
from tracefold.platform.postgres.migrations import latest_migration_version

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "db-schema.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_db_schema.py — do not hand-edit -->\n\n"
TEST_POSTGRES_DSN_ENV = "TRACEFOLD_TEST_POSTGRES_DSN"
EXPECTED_TABLES_AT_HEAD = frozenset({"alembic_version", "workers_runtime", *NEWS_TABLES, *TRADING_TABLES})


def _sqlalchemy_url(settings: Settings | None) -> str:
    test_dsn = os.environ.get(TEST_POSTGRES_DSN_ENV, "").strip()
    if test_dsn:
        dsn = test_dsn
    else:
        if settings is None:
            settings = load_settings(require_ws_token=False)
        dsn = local_docker_host_dsn(
            with_password_from_file(
                settings.storage.postgres.dsn,
                settings.postgres_password_file(),
            )
        )
    if dsn.startswith("postgresql://"):
        return "postgresql+psycopg://" + dsn.removeprefix("postgresql://")
    return dsn


def _require_database_at_alembic_head(connection: Connection) -> None:
    expected = latest_migration_version()
    versions = [
        str(version)
        for version in connection.exec_driver_sql("SELECT version_num FROM alembic_version ORDER BY version_num")
        .scalars()
        .all()
    ]
    if versions != [expected]:
        actual = ",".join(versions) if versions else "<missing>"
        raise RuntimeError(f"db_schema_generation_requires_alembic_head: expected={expected} actual={actual}")


def _require_expected_tables(table_names: list[str]) -> None:
    actual = frozenset(table_names)
    if actual != EXPECTED_TABLES_AT_HEAD:
        missing = ",".join(sorted(EXPECTED_TABLES_AT_HEAD - actual)) or "<none>"
        unexpected = ",".join(sorted(actual - EXPECTED_TABLES_AT_HEAD)) or "<none>"
        raise RuntimeError(f"db_schema_generation_table_set_mismatch: missing={missing} unexpected={unexpected}")


def main() -> None:
    settings = None if os.environ.get(TEST_POSTGRES_DSN_ENV, "").strip() else load_settings(require_ws_token=False)
    engine = create_engine(_sqlalchemy_url(settings), pool_pre_ping=True)
    try:
        with engine.connect() as connection:
            _require_database_at_alembic_head(connection)
            inspector = inspect(connection)
            table_names = sorted(inspector.get_table_names(schema="public"))
            _require_expected_tables(table_names)
            body = ["# Database Columns", ""]
            for table in table_names:
                body.append(f"## `{table}`")
                body.append("")
                body.append("| Column | Type | Nullable | Default |")
                body.append("|--------|------|----------|---------|")
                body.extend(
                    f"| `{col['name']}` | `{col['type']}` | {col.get('nullable', True)} | `{col.get('default')}` |"
                    for col in inspector.get_columns(table, schema="public")
                )
                body.append("")
        while body and body[-1] == "":
            body.pop()
        OUTPUT.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")
    finally:
        engine.dispose()


if __name__ == "__main__":
    main()
