# scripts/regen_cli_help.py
"""Regenerate docs/generated/cli-help.md from `tracefold --help`."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tracefold.app.cli.parser import build_parser

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "cli-help.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_cli_help.py — do not hand-edit -->\n\n"


def _command_parsers(
    parser: argparse.ArgumentParser,
    prefix: tuple[str, ...] = (),
) -> list[tuple[str, argparse.ArgumentParser]]:
    commands: list[tuple[str, argparse.ArgumentParser]] = []
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name, child in action.choices.items():
            path = (*prefix, name)
            commands.append((" ".join(path), child))
            commands.extend(_command_parsers(child, path))
    return commands


def render_cli_help() -> str:
    parser = build_parser()
    body = ["# CLI Help", "", "## Top level", "", "```", parser.format_help(), "```", ""]
    for path, child in _command_parsers(parser):
        body += [f"## `{path}`", "", "```", child.format_help(), "```", ""]
    return HEADER + "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/cli-help.md from `tracefold --help`")
    parser.add_argument("--check", action="store_true", help="exit non-zero if docs/generated/cli-help.md is stale")
    args = parser.parse_args()

    rendered = render_cli_help()
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(
                "docs/generated/cli-help.md is stale; run `uv run python scripts/regen_cli_help.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[1]).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
