# scripts/regen_openapi.py
"""Regenerate docs/generated/openapi.json from FastAPI app.openapi().

This is the source of truth for the auto-generated OpenAPI TS bindings
(web/src/lib/types/openapi.ts, generated by openapi-typescript).
Run via `make regen-contract` to regenerate both JSON and TS artefacts.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "generated" / "openapi.json"

sys.path.insert(0, str(ROOT / "src"))


def main() -> int:
    from tracefold.app.http.app import create_app  # type: ignore[import-not-found]
    from tracefold.platform.config.settings import Settings  # type: ignore[import-not-found]

    # Pass a minimal Settings object so we don't call load_settings() which reads
    # the local config.yaml (and requires ws_token + valid local config at dev time).
    # The lifespan (Postgres, workers) only runs under uvicorn — not during schema gen.
    settings = Settings(ws_token="schema-gen-placeholder")
    app = create_app(settings=settings)
    schema = app.openapi()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(json.dumps(schema))} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
