# scripts/regen_db_schema.py
"""Regenerate docs/generated/db-schema.md from Alembic head + pg_catalog introspection.

Requires Postgres reachable via the standard project config.

Import note: the storage module uses psycopg directly (no SQLAlchemy engine).
We follow the same pattern as src/tracefold/storage/alembic/env.py:
build a postgresql+psycopg URL via local_docker_host_dsn / with_password_from_file
and pass it to sqlalchemy.create_engine for inspection-only access.
"""

from __future__ import annotations

import os
from collections.abc import Sequence
from pathlib import Path

from sqlalchemy import create_engine, inspect
from sqlalchemy.engine import Connection

from tracefold.platform.config.settings import Settings, load_settings
from tracefold.platform.postgres.postgres_client import local_docker_host_dsn, with_password_from_file
from tracefold.platform.postgres.postgres_migrations import latest_migration_version

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "db-schema.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_db_schema.py — do not hand-edit -->\n\n"
TEST_POSTGRES_DSN_ENV = "GMGN_TEST_POSTGRES_DSN"
RETIRED_TABLES_AT_HEAD = frozenset(
    {
        "cex_derivative_series",
        "cex_detail_snapshots",
        "cex_oi_radar_publication_state",
        "cex_oi_radar_rows",
        "discussion_digest_dirty_targets",
        "account_profiles",
        "account_quality_snapshots",
        "account_token_call_stats",
        "account_token_alerts",
        "macro_daily_briefs",
        "macro_import_runs",
        "market_tick_current_dirty_targets",
        "model_runs",
        "narrative_admission_dirty_targets",
        "narrative_admissions",
        "narrative_model_runs",
        "news_item_agent_briefs",
        "news_item_agent_runs",
        "news_identity_features",
        "news_projection_frontiers",
        "news_similarity_edges",
        "news_story_aliases",
        "news_story_agent_briefs",
        "news_story_agent_runs",
        "news_story_input_state",
        "news_source_quality_rows",
        "notification_deliveries",
        "notification_reads",
        "notifications",
        "projects",
        "projection_offsets",
        "projection_runs",
        "projection_dirty_ranges",
        "pulse_agent_eval_cases",
        "pulse_agent_eval_results",
        "pulse_agent_jobs",
        "pulse_agent_run_steps",
        "pulse_agent_runs",
        "pulse_agent_runtime_versions",
        "pulse_candidate_edge_state",
        "pulse_candidate_run_budget",
        "pulse_candidates",
        "pulse_evidence_packets",
        "pulse_playbook_outcomes",
        "pulse_playbook_snapshots",
        "pulse_target_run_budget",
        "pulse_trigger_dirty_targets",
        "registry_aliases",
        "registry_versions",
        "schema_migrations",
        "token_aliases",
        "token_capture_tier",
        "token_capture_tier_dirty_targets",
        "token_discussion_digests",
        "token_flow_window_snapshots",
        "token_mention_semantics",
        "token_radar_publications",
        "token_radar_source_dirty_events",
        "token_radar_storage_maintenance_runs",
        "token_score_evaluations",
        "token_social_bucket_authors",
        "token_social_buckets",
    }
)


def _sqlalchemy_url(settings: Settings | None) -> str:
    test_dsn = os.environ.get(TEST_POSTGRES_DSN_ENV, "").strip()
    if test_dsn:
        dsn = test_dsn
    else:
        if settings is None:
            settings = load_settings(require_ws_token=False)
        dsn = local_docker_host_dsn(
            with_password_from_file(
                settings.postgres_dsn("serve"),
                settings.postgres_password_file("serve"),
            )
        )
    if dsn.startswith("postgresql://"):
        return "postgresql+psycopg://" + dsn.removeprefix("postgresql://")
    return dsn


def _require_database_at_alembic_head(connection: Connection) -> None:
    expected = latest_migration_version()
    versions = [
        str(version)
        for version in connection.exec_driver_sql("SELECT version_num FROM alembic_version ORDER BY version_num")
        .scalars()
        .all()
    ]
    if versions != [expected]:
        actual = ",".join(versions) if versions else "<missing>"
        raise RuntimeError(f"db_schema_generation_requires_alembic_head: expected={expected} actual={actual}")


def _require_retired_tables_absent(table_names: Sequence[str]) -> None:
    retired_tables_present = sorted(RETIRED_TABLES_AT_HEAD.intersection(table_names))
    if retired_tables_present:
        raise RuntimeError(
            "db_schema_generation_requires_hard_cut_schema: retired_tables_present=" + ",".join(retired_tables_present)
        )


def main() -> None:
    settings = None if os.environ.get(TEST_POSTGRES_DSN_ENV, "").strip() else load_settings(require_ws_token=False)
    engine = create_engine(_sqlalchemy_url(settings), pool_pre_ping=True)
    try:
        with engine.connect() as connection:
            _require_database_at_alembic_head(connection)
            inspector = inspect(connection)
            table_names = sorted(inspector.get_table_names(schema="public"))
            _require_retired_tables_absent(table_names)
            body = ["# Database Schema", ""]
            for table in table_names:
                body.append(f"## `{table}`")
                body.append("")
                body.append("| Column | Type | Nullable | Default |")
                body.append("|--------|------|----------|---------|")
                body.extend(
                    f"| `{col['name']}` | `{col['type']}` | {col.get('nullable', True)} | `{col.get('default')}` |"
                    for col in inspector.get_columns(table, schema="public")
                )
                body.append("")
        while body and body[-1] == "":
            body.pop()
        OUTPUT.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")
    finally:
        engine.dispose()


if __name__ == "__main__":
    main()
