# scripts/regen_score_versions.py
"""Regenerate docs/generated/score-versions.md by scanning src/ for score/version literals."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUTPUT = ROOT / "docs" / "generated" / "score-versions.md"
HEADER = "<!-- AUTO-GENERATED by scripts/regen_score_versions.py — do not hand-edit -->\n\n"
PATTERNS = (re.compile(r'score_version\s*=\s*[\'"]([^\'"]+)[\'"]'),)


def _render() -> str:
    rows: list[tuple[str, str, int, str]] = []
    for path in sorted(SRC.rglob("*.py")):
        rel = path.relative_to(ROOT).as_posix()
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for pattern in PATTERNS:
                rows.extend((match.group(1), rel, lineno, line.strip()) for match in pattern.finditer(line))
    body = ["# Score Versions", "", "| Version | File | Line | Context |", "|---------|------|------|---------|"]
    for version, rel, lineno, context in sorted(rows):
        body.append(f"| `{version}` | `{rel}` | {lineno} | `{context}` |")
    return HEADER + "\n".join(body) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/generated/score-versions.md from source literals")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/generated/score-versions.md is stale",
    )
    args = parser.parse_args()

    rendered = _render()
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(
                "docs/generated/score-versions.md is stale; run `uv run python scripts/regen_score_versions.py`.",
            )
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[1]).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
